create table if not exists public.hub_eventos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  data date not null,
  horario time not null,
  responsavel text not null,
  tipo text not null default 'Evento',
  descricao text,
  created_by text default 'Sistema',
  created_at timestamptz not null default now()
);

alter table public.hub_eventos enable row level security;

drop policy if exists "hub_eventos_public_read" on public.hub_eventos;
drop policy if exists "hub_eventos_public_insert" on public.hub_eventos;
drop policy if exists "hub_eventos_public_update" on public.hub_eventos;
drop policy if exists "hub_eventos_public_delete" on public.hub_eventos;

create policy "hub_eventos_public_read"
on public.hub_eventos
for select to anon, authenticated
using (true);

create policy "hub_eventos_public_insert"
on public.hub_eventos
for insert to anon, authenticated
with check (true);

create policy "hub_eventos_public_update"
on public.hub_eventos
for update to anon, authenticated
using (true)
with check (true);

create policy "hub_eventos_public_delete"
on public.hub_eventos
for delete to anon, authenticated
using (true);

grant select, insert, update, delete on public.hub_eventos to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
