create table if not exists public.hub_chamados (
  id bigint generated by default as identity primary key,
  solicitante text not null,
  telefone text not null default '',
  unidade text not null,
  setor text not null default '',
  epis text not null,
  observacoes text,
  status text not null default 'Aberto',
  created_by text default 'Publico',
  created_at timestamptz not null default now()
);

alter table public.hub_chamados enable row level security;

drop policy if exists "hub_chamados_public_read" on public.hub_chamados;
drop policy if exists "hub_chamados_public_insert" on public.hub_chamados;

create policy "hub_chamados_public_read"
on public.hub_chamados
for select
to anon, authenticated
using (true);

create policy "hub_chamados_public_insert"
on public.hub_chamados
for insert
to anon, authenticated
with check (true);

grant select, insert on public.hub_chamados to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

do $$
begin
  alter publication supabase_realtime add table public.hub_chamados;
exception
  when duplicate_object then null;
end $$;
