create table if not exists public.hub_users (
  id bigint generated by default as identity primary key,
  nome text not null,
  senha text not null,
  cargo text not null default '',
  created_by text not null default 'Sistema',
  created_at timestamptz not null default now()
);

create unique index if not exists hub_users_nome_lower_idx
on public.hub_users (lower(nome));

alter table public.hub_users
add column if not exists created_by text not null default 'Sistema';

alter table public.hub_users
add column if not exists cargo text not null default '';

alter table public.hub_users enable row level security;

drop policy if exists "hub_users_public_read" on public.hub_users;
drop policy if exists "hub_users_public_insert" on public.hub_users;
drop policy if exists "hub_users_public_update" on public.hub_users;
drop policy if exists "hub_users_public_delete" on public.hub_users;

create policy "hub_users_public_read" on public.hub_users
for select to anon, authenticated
using (true);

create policy "hub_users_public_insert" on public.hub_users
for insert to anon, authenticated
with check (true);

create policy "hub_users_public_update" on public.hub_users
for update to anon, authenticated
using (true);

create policy "hub_users_public_delete" on public.hub_users
for delete to anon, authenticated
using (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.hub_users to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into public.hub_users (nome, senha, cargo, created_by)
values
  ('Ariel', 'arielc', 'RH', 'Sistema'),
  ('Andrei', '1208', 'RH', 'Sistema'),
  ('Patricia', '1102', 'RH', 'Sistema'),
  ('Dani', '926710', 'RH', 'Sistema'),
  ('Vanessa', '521216', 'RH', 'Sistema')
on conflict ((lower(nome))) do update set
  nome = excluded.nome,
  senha = excluded.senha,
  cargo = excluded.cargo;
