create table if not exists public.hub_denuncias (
  id bigint generated by default as identity primary key,
  identificacao text not null default 'Anonimo',
  categoria text not null,
  descricao text not null,
  status text not null default 'Aberta',
  created_at timestamptz not null default now()
);

create table if not exists public.hub_chat_messages (
  id bigint generated by default as identity primary key,
  autor text not null default 'Equipe RH',
  mensagem text,
  canal text not null default 'geral',
  arquivo_nome text,
  arquivo_tamanho bigint,
  arquivo_tipo text,
  arquivo_url text,
  created_at timestamptz not null default now(),
  constraint hub_chat_message_has_content check (
    nullif(trim(coalesce(mensagem, '')), '') is not null or arquivo_url is not null
  )
);

alter table public.hub_chat_messages
add column if not exists canal text not null default 'geral';

create table if not exists public.hub_malotes (
  id bigint generated by default as identity primary key,
  destino text not null,
  epis text not null,
  status text not null default 'Separacao',
  created_at timestamptz not null default now()
);

create table if not exists public.hub_vagas (
  id bigint generated by default as identity primary key,
  cargo text not null,
  projeto text not null,
  status text not null default 'Aberta',
  created_at timestamptz not null default now()
);

create table if not exists public.hub_candidaturas (
  id bigint generated by default as identity primary key,
  vaga_id bigint not null references public.hub_vagas(id),
  nome text not null,
  cpf text not null,
  curriculo_url text not null,
  created_at timestamptz not null default now(),
  constraint unique_cpf_per_vaga unique(vaga_id, cpf)
);

alter table public.hub_denuncias enable row level security;
alter table public.hub_chat_messages enable row level security;
alter table public.hub_malotes enable row level security;
alter table public.hub_vagas enable row level security;
alter table public.hub_candidaturas enable row level security;

drop policy if exists "hub_denuncias_public_read" on public.hub_denuncias;
drop policy if exists "hub_denuncias_public_insert" on public.hub_denuncias;
drop policy if exists "hub_denuncias_public_update" on public.hub_denuncias;
drop policy if exists "hub_chat_public_read" on public.hub_chat_messages;
drop policy if exists "hub_chat_public_insert" on public.hub_chat_messages;
drop policy if exists "hub_malotes_public_read" on public.hub_malotes;
drop policy if exists "hub_malotes_public_insert" on public.hub_malotes;
drop policy if exists "hub_vagas_public_read" on public.hub_vagas;
drop policy if exists "hub_vagas_public_insert" on public.hub_vagas;
drop policy if exists "hub_candidaturas_public_read" on public.hub_candidaturas;
drop policy if exists "hub_candidaturas_public_insert" on public.hub_candidaturas;

create policy "hub_denuncias_public_read" on public.hub_denuncias for select to anon, authenticated using (true);
create policy "hub_denuncias_public_insert" on public.hub_denuncias for insert to anon, authenticated with check (true);
create policy "hub_denuncias_public_update" on public.hub_denuncias for update to anon, authenticated using (true);
create policy "hub_chat_public_read" on public.hub_chat_messages for select to anon, authenticated using (true);
create policy "hub_chat_public_insert" on public.hub_chat_messages for insert to anon, authenticated with check (true);
create policy "hub_malotes_public_read" on public.hub_malotes for select to anon, authenticated using (true);
create policy "hub_malotes_public_insert" on public.hub_malotes for insert to anon, authenticated with check (true);
create policy "hub_vagas_public_read" on public.hub_vagas for select to anon, authenticated using (true);
create policy "hub_vagas_public_insert" on public.hub_vagas for insert to anon, authenticated with check (true);
create policy "hub_candidaturas_public_read" on public.hub_candidaturas for select to anon, authenticated using (true);
create policy "hub_candidaturas_public_insert" on public.hub_candidaturas for insert to anon, authenticated with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.hub_denuncias to anon, authenticated;
grant select, insert on public.hub_chat_messages to anon, authenticated;
grant select, insert on public.hub_malotes to anon, authenticated;
grant select, insert on public.hub_vagas to anon, authenticated;
grant select, insert on public.hub_candidaturas to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('hub-chat-files', 'hub-chat-files', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('hub-curriculos', 'hub-curriculos', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "hub_chat_files_public_read" on storage.objects;
drop policy if exists "hub_chat_files_public_upload" on storage.objects;
drop policy if exists "hub_chat_files_public_update" on storage.objects;
drop policy if exists "hub_chat_files_public_delete" on storage.objects;
drop policy if exists "hub_curriculos_public_read" on storage.objects;
drop policy if exists "hub_curriculos_public_upload" on storage.objects;
drop policy if exists "hub_curriculos_public_update" on storage.objects;
drop policy if exists "hub_curriculos_public_delete" on storage.objects;

create policy "hub_chat_files_public_read" on storage.objects
for select to anon, authenticated
using (bucket_id = 'hub-chat-files');

create policy "hub_chat_files_public_upload" on storage.objects
for insert to anon, authenticated
with check (bucket_id = 'hub-chat-files');

create policy "hub_chat_files_public_update" on storage.objects
for update to anon, authenticated
using (bucket_id = 'hub-chat-files');

create policy "hub_chat_files_public_delete" on storage.objects
for delete to anon, authenticated
using (bucket_id = 'hub-chat-files');

create policy "hub_curriculos_public_read" on storage.objects
for select to anon, authenticated
using (bucket_id = 'hub-curriculos');

create policy "hub_curriculos_public_upload" on storage.objects
for insert to anon, authenticated
with check (bucket_id = 'hub-curriculos');

create policy "hub_curriculos_public_update" on storage.objects
for update to anon, authenticated
using (bucket_id = 'hub-curriculos');

create policy "hub_curriculos_public_delete" on storage.objects
for delete to anon, authenticated
using (bucket_id = 'hub-curriculos');
