$ErrorActionPreference = "Stop"

$ProjectRoot = Resolve-Path (Join-Path $PSScriptRoot "..")

function Read-ProjectFile {
  param([Parameter(Mandatory = $true)][string]$RelativePath)
  return [System.IO.File]::ReadAllText((Join-Path $ProjectRoot $RelativePath))
}

function Assert-True {
  param(
    [Parameter(Mandatory = $true)][bool]$Condition,
    [Parameter(Mandatory = $true)][string]$Message
  )
  if (-not $Condition) {
    throw "FAIL: $Message"
  }
  Write-Host "PASS: $Message"
}

function Assert-MatchText {
  param(
    [Parameter(Mandatory = $true)][string]$Text,
    [Parameter(Mandatory = $true)][string]$Pattern,
    [Parameter(Mandatory = $true)][string]$Message
  )
  Assert-True -Condition ([regex]::IsMatch($Text, $Pattern, [System.Text.RegularExpressions.RegexOptions]::Singleline)) -Message $Message
}

function Test-LoginHtml {
  $path = Join-Path $ProjectRoot "login.html"
  $bytes = [System.IO.File]::ReadAllBytes($path)
  $text = Read-ProjectFile "login.html"

  Assert-True -Condition ($bytes.Length -gt 3) -Message "login.html nao esta vazio"
  Assert-True -Condition (-not ($bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF)) -Message "login.html nao possui BOM UTF-8 no inicio"
  Assert-True -Condition ($text.StartsWith("<!doctype html>")) -Message "login.html inicia diretamente com <!doctype html>"
  Assert-MatchText $text 'Content-Security-Policy' "login.html possui CSP"
  Assert-MatchText $text 'object-src ''none''' "CSP bloqueia object-src"
  Assert-MatchText $text 'frame-ancestors ''none''' "CSP bloqueia embed por frame"
  Assert-MatchText $text 'form id="login-form" method="post" action="login.html" autocomplete="off"' "formulario de login nunca envia credenciais por GET"
  Assert-MatchText $text 'name="identificador"[^>]*autocomplete="off"' "campo e-mail/CPF desativa autocomplete"
  Assert-MatchText $text 'name="senha"[^>]*autocomplete="off"' "campo senha desativa autocomplete"
  Assert-MatchText $text 'hub-postgres-client\.js\?v=auth-cookie-v1[\s\S]*login-submit\.js\?v=login-submit-v2[\s\S]*script\.js\?v=auth-persist-v32' "login possui controlador de autenticacao antes do script principal"
}

function Test-ClientSecurityFunctions {
  $script = Read-ProjectFile "script.js"
  $index = Read-ProjectFile "index.html"
  $vagas = Read-ProjectFile "vagas.html"
  $chamados = Read-ProjectFile "chamados.html"
  $docsFredy = Read-ProjectFile "documentos-fredy.html"
  $docsBesten = Read-ProjectFile "documentos-besten.html"
  $docsAchei = Read-ProjectFile "documentos-achei.html"
  $docsTrinca = Read-ProjectFile "documentos-trinca.html"
  $style = Read-ProjectFile "style.css"
  $companyBirthdays = Read-ProjectFile "assets/company-birthdays.js"
  $accountLoadingGuard = Read-ProjectFile "account-loading-guard.js"
  $postgresClient = Read-ProjectFile "hub-postgres-client.js"
  $contractorApi = Read-ProjectFile "api/contractor-documents.js"
  $recordsApi = Read-ProjectFile "api/records.js"
  $authApi = Read-ProjectFile "api/auth.js"

  Assert-MatchText $script 'function escapeHtml\(value\).*replaceAll\("&", "&amp;"\).*replaceAll\("<", "&lt;"\).*replaceAll\(">", "&gt;"\).*replaceAll\(''"'', "&quot;"\).*replaceAll\("''", "&#039;"\)' "escapeHtml escapa caracteres perigosos"
  Assert-MatchText $recordsApi 'JSON_COLUMNS[\s\S]*"hub_documentos_contratados"[\s\S]*"documentos"[\s\S]*"hub_malotes"[\s\S]*"colaboradores"[\s\S]*"hub_quadros"[\s\S]*"listas"[\s\S]*"hub_users"[\s\S]*"configuracoes"' "API serializa colunas JSON conhecidas"
  Assert-MatchText $recordsApi 'function normalizeDbValue[\s\S]*JSON\.stringify\(value\)[\s\S]*function placeholderFor[\s\S]*::jsonb' "API grava arrays e objetos como jsonb"
  Assert-MatchText $authApi 'Set-Cookie[\s\S]*hub_auth_session[\s\S]*Max-Age=2592000' "API auth grava cookie persistente"
  Assert-MatchText $authApi 'ensureSessionVersionColumn[\s\S]*session_version[\s\S]*export async function validateAuthSession[\s\S]*action === "session"[\s\S]*validateAuthSession\(req\)' "API auth valida sessao exclusiva por usuario"
  Assert-MatchText $authApi 'function publicUser\(row\)[\s\S]*genericName[\s\S]*displayName[\s\S]*user_metadata: \{ nome: displayName' "API nunca retorna Usuario quando existe identificador real"
  Assert-MatchText $authApi 'action === "logout"[\s\S]*clearAuthCookie\(res\)' "API auth limpa cookie no logout"
  Assert-MatchText (Read-ProjectFile "api/auth/heartbeat.js") 'validateAuthSession\(req\)[\s\S]*json\(res, 401[\s\S]*Sessao encerrada por outro login' "heartbeat encerra maquinas com sessao antiga"
  Assert-True -Condition (-not (($script + $postgresClient) -match '<<<<<<<|>>>>>>>')) -Message "scripts nao possuem marcadores de conflito"
  Assert-MatchText $index 'auth-entry\.js\?v=auth-entry-v15[\s\S]*style\.css\?v=auth-persist-v22[\s\S]*hub-postgres-client\.js\?v=auth-cookie-v1[\s\S]*script\.js\?v=auth-persist-v32[\s\S]*auth-display-guard\.js\?v=auth-display-v4' "HUB autentica sem exibir o painel antes da validacao"
  Assert-MatchText $index '<div class="app-shell" id="app-shell">' "HUB nao embute a tela de carregamento no painel"
  Assert-True -Condition (-not ($index -match 'account-loading-guard\.js|Carregando sua conta')) -Message "index.html nao possui a tela de carregamento"
  $loading = Read-ProjectFile "account-loading.html"
  $loadingScript = Read-ProjectFile "account-loading.js"
  Assert-MatchText $loading '<main class="account-loading-screen"[\s\S]*Restaurando sua conta' "tela de carregamento possui HTML proprio"
  Assert-MatchText $loading 'account-loading\.js\?v=auth-loading-v2' "tela de carregamento quebra cache do navegador"
  Assert-MatchText $loadingScript 'MINIMUM_LOADING_MS = 1000[\s\S]*function finishLoading\([\s\S]*setTimeout\(callback, remaining\)[\s\S]*function redirectToLogin\(\)[\s\S]*POSTGRES_SESSION_KEY[\s\S]*PERSISTED_USER_KEY[\s\S]*removeItem\(key\)[\s\S]*fetch\("/api/auth"[\s\S]*action: "session"[\s\S]*redirectToLogin\(\)' "tela de carregamento aguarda 1 segundo e envia sessao invalida para login"
  Assert-MatchText $loadingScript 'window\.localStorage\.setItem\(VERIFIED_KEY, "1"\)[\s\S]*finishLoading\(\(\) => window\.location\.replace\("index\.html"\)\)' "index so e liberado depois da autenticacao confirmada"
  Assert-MatchText (Read-ProjectFile "auth-entry.js") 'AUTH_REQUEST_TIMEOUT_MS = 3000[\s\S]*fetch\("/api/auth"[\s\S]*credentials: "same-origin"[\s\S]*action: "session"[\s\S]*signal: controller.signal[\s\S]*if \(!response\.ok \|\| !persistAuthenticatedSession\(result\?\.session\)\)[\s\S]*redirectToLogin\(\)[\s\S]*window\.__hubAuthEntryPromise' "F5 exige autenticacao persistente antes de carregar o painel"
  Assert-MatchText (Read-ProjectFile "auth-entry.js") 'async function hasRecentActivity\(\)[\s\S]*is_online[\s\S]*last_seen[\s\S]*age <= 3000' "atividade recente continua disponivel para restauracao"
  Assert-MatchText $script 'sendHeartbeat\(true\);[\s\S]*setInterval\(\(\) => sendHeartbeat\(true\), 2000\)' "atividade do usuario e atualizada a cada 2 segundos"
  Assert-True -Condition (-not $script.Contains('sendOfflineBeacon')) -Message "F5 nao marca o usuario offline antes de restaurar a sessao"
  Assert-MatchText $script 'window\.__hubAuthEntryPromise[\s\S]*const entryAuthenticated = await window\.__hubAuthEntryPromise[\s\S]*if \(!entryAuthenticated\) return false;' "index aguarda restauracao local antes de inicializar"
  Assert-MatchText $script 'if \(!authSession\?\.user\)[\s\S]*clearAuthenticatedUser\(\)[\s\S]*window\.location\.replace\(`login\.html\?next=' "falha de autenticacao envia para login"
  Assert-MatchText $accountLoadingGuard 'const POSTGRES_SESSION_KEY = "hub-postgres-session"[\s\S]*const postgresUser = readJson\(POSTGRES_SESSION_KEY\)\?\.user[\s\S]*postgresUser\?\.email[\s\S]*normalizedName !== "usuario"[\s\S]*if \(active && hasStoredIdentity\(\)\)' "guard externo reconhece sessao postgres persistida sem destravar Usuario generico"
  Assert-MatchText $accountLoadingGuard 'function redirectToLogin\(\)[\s\S]*window\.location\.replace\(`login\.html\?next=' "guard externo envia para login sem sessao salva"
  Assert-MatchText $style 'html\.auth-entry-pending body[\s\S]*\.account-loading-page[\s\S]*\.account-loading-screen[\s\S]*\.account-loading-card' "index permanece oculto enquanto autentica"
  $encodingArtifacts = @(([char]0x00C3), ([char]0x00C2), ([char]0x00E2))
  Assert-True -Condition (-not ($encodingArtifacts | Where-Object { $index.Contains([string]$_) })) -Message "index.html nao possui caracteres corrompidos por encoding"
  Assert-MatchText $script 'function isValidCpf\(value\).*\/\^\\d\{11\}\$\/\.test\(cpf\).*\/\^\(\\d\)\\1\{10\}\$\/\.test\(cpf\)' "validacao de CPF rejeita formato invalido e sequencias repetidas"
  Assert-MatchText $script 'RESUME_MAX_SIZE_BYTES\s*=\s*5\s*\*\s*1024\s*\*\s*1024' "curriculo limitado a 5 MB no cliente"
  Assert-MatchText $script 'RESUME_ALLOWED_EXTENSIONS\s*=\s*new Set\(\["pdf", "doc", "docx"\]\)' "curriculo permite apenas pdf/doc/docx"
  Assert-MatchText $script 'RESUME_ALLOWED_MIME_TYPES\s*=\s*new Set\(\[[\s\S]*application\/pdf[\s\S]*application\/msword[\s\S]*officedocument\.wordprocessingml\.document' "curriculo valida MIME permitido"
  Assert-MatchText $script 'function uploadChatFile\(file\).*safeName\s*=\s*file\.name\.replace\(/[^/]+/gi, "-"\)' "upload de chat sanitiza nome do arquivo"
  Assert-MatchText $script 'function uploadChatFile\(file\)[\s\S]*postgresClient\?\.storage\?\.from[\s\S]*await uploadPublicFile\(file, path\)' "upload de chat usa API local se storage falhar"
  Assert-MatchText $script 'async function createPrivateStorageUrl\(bucket, value\)[\s\S]*createSignedUrl[\s\S]*return `/api/files\?path=\$\{encodeURIComponent\(path\)\}`' "preview do chat usa API local se assinatura falhar"
  Assert-MatchText $index 'id="chat-file"[^>]*multiple[^>]*accept="[^"]*image/png[^"]*image/jpeg[^"]*video/mp4[^"]*audio/mpeg[^"]*audio/wav[^"]*audio/ogg[^"]*audio/mp4[^"]*\.m4a' "input do chat aceita multiplas imagens videos e audios"
  Assert-MatchText $index 'id="chat-emoji-button"[^>]*data-action="toggle-chat-emoji-menu"[\s\S]*id="chat-emoji-menu"[^>]*hidden' "chat possui botao e menu de emojis"
  Assert-MatchText $index 'class="chat-message-filter" id="chat-message-filter-wrap"[^>]*hidden[\s\S]*id="chat-message-filter"[^>]*type="search"[^>]*placeholder="Filtrar mensagens deste chat"' "chat possui filtro de mensagens especificas oculto por padrao"
  Assert-MatchText $index 'id="chat-attach-menu-button"[^>]*data-action="toggle-chat-attach-menu"[^>]*>\+<\/button>[\s\S]*id="chat-attach-menu"[^>]*hidden[\s\S]*data-attach-type="document"[\s\S]*Documento[\s\S]*data-attach-type="media"[\s\S]*Fotos e v&iacute;deos[\s\S]*data-attach-type="poll"[\s\S]*Enquete' "chat troca anexar por botao mais com menu de opcoes essenciais"
  Assert-True -Condition (-not ($index -match 'data-attach-type="camera"|data-attach-type="audio"|data-attach-type="contact"|data-attach-type="event"')) -Message "menu de anexos do chat exibe somente documento fotos/videos e enquete"
  Assert-True -Condition (-not $index.Contains('>Anexar arquivo</label>')) -Message "chat nao exibe mais botao textual Anexar arquivo"
  Assert-MatchText $index '<textarea name="mensagem"[\s\S]*<button class="record-audio-button" id="record-audio-button" type="button"[^>]*aria-label="Gravar .udio"[^>]*>[\s\S]*assets/microphone-icon\.png[\s\S]*?</button>\s*<button class="primary-button send-button" type="submit">Enviar</button>' "chat possui botao minimalista com icone de microfone antes de enviar"
  Assert-MatchText $index 'id="recording-duration"[^>]*aria-live="polite"[^>]*>00:00</span>' "botao de audio possui contador de duracao"
  Assert-MatchText $script 'let activeChatChannel = "";' "chat nao abre canal automaticamente ao entrar em Comunicacao RH"
  Assert-MatchText $script 'function getActiveChatChannel\(\)[\s\S]*return channels\.find\(\(channel\) => channel\.id === activeChatChannel\) \|\| null' "chat nao usa fallback automatico para primeiro canal"
  Assert-MatchText $script 'if \(activeChatChannel && \(!channels\.some\(\(channel\) => channel\.id === activeChatChannel\)' "lista de canais nao seleciona o primeiro canal automaticamente"
  Assert-MatchText $script 'Selecione um canal de comunica..o para visualizar as mensagens' "chat orienta o usuario a escolher um canal"
  Assert-MatchText $index 'id="create-poll-button"[^>]*data-action="open-chat-poll"[^>]*hidden' "chat possui botao de enquete inicialmente oculto"
  Assert-MatchText $script 'const CHAT_POLL_PREFIX = "__HUB_POLL__:"' "chat possui prefixo seguro para mensagens de enquete"
  Assert-MatchText $script 'function parseChatPollMessage\(value\)[\s\S]*text\.startsWith\(CHAT_POLL_PREFIX\)[\s\S]*JSON\.parse' "chat interpreta mensagens de enquete"
  Assert-MatchText $script 'function serializeChatPoll\(poll\)[\s\S]*CHAT_POLL_PREFIX[\s\S]*JSON\.stringify' "chat serializa enquetes para persistencia"
  Assert-MatchText $script 'function renderChatPoll\(item, poll\)[\s\S]*data-action="vote-chat-poll"[\s\S]*chat-poll-bar' "chat renderiza enquete com opcoes votaveis"
  Assert-MatchText $script 'function renderChat\(\)[\s\S]*const pollMenuOption = document\.querySelector\(.\[data-attach-type="poll"\].\)[\s\S]*isGeneralChatChannel\(activeChannel\.id\)[\s\S]*pollMenuOption\) pollMenuOption\.hidden = !canCreatePoll' "opcao de enquete aparece somente em grupos"
  Assert-MatchText $script 'function createChatPollOptionField\(index, required = false\)[\s\S]*const canRemove = index > 2[\s\S]*name="opcao"[\s\S]*required \?[\s\S]*data-action="remove-chat-poll-option"' "enquete cria campos dinamicos e botao excluir apenas em opcoes extras"
  Assert-MatchText $script 'function refreshChatPollOptionFields\(formElement\)[\s\S]*input\.required = optionNumber <= 2[\s\S]*removeButton\.hidden = optionNumber <= 2' "enquete mantem duas primeiras opcoes obrigatorias e sem exclusao"
  Assert-MatchText $script 'function addChatPollOptionField\(formElement\)[\s\S]*currentTotal >= 8[\s\S]*insertAdjacentHTML\("beforeend", createChatPollOptionField\(currentTotal \+ 1\)\)' "enquete possui botao para adicionar opcoes"
  Assert-MatchText $script 'function removeChatPollOptionField\(button\)[\s\S]*fields\.length <= 2[\s\S]*pelo menos 2 op..es[\s\S]*closest\("\[data-chat-poll-option\]"\)\?\.remove\(\)[\s\S]*refreshChatPollOptionFields\(formElement\)' "enquete permite excluir opcoes somente acima do minimo de duas"
  Assert-MatchText $script 'function showChatPollModal\(\)[\s\S]*isGeneralChatChannel\(activeChannel\.id\)[\s\S]*id="chat-poll-form"[\s\S]*id="chat-poll-options"[\s\S]*createChatPollOptionField\(1, true\)[\s\S]*createChatPollOptionField\(2, true\)[\s\S]*data-action="add-chat-poll-option"[\s\S]*Adicionar op..o' "modal de enquete inicia com pergunta duas opcoes e botao adicionar opcao"
  Assert-MatchText $script 'async function criarEnqueteChat\(formElement\)[\s\S]*addItem\("comunicados"[\s\S]*serializeChatPoll' "criacao de enquete salva no chat"
  Assert-MatchText $script 'async function votarEnqueteChat\(messageId, optionIndex\)[\s\S]*poll\.votes\[voter\] = selectedIndex[\s\S]*updateItem\("comunicados"' "votacao de enquete atualiza a mensagem no PostgreSQL"
  Assert-MatchText $script 'function handleChatAttachOption\(type\)[\s\S]*case "document":[\s\S]*case "media":[\s\S]*case "poll":[\s\S]*showChatPollModal\(\)' "menu mais abre documentos midia e enquete"
  Assert-True -Condition (-not ($script -match 'case "camera":|case "audio":|case "contact":|case "event":')) -Message "handler do menu de anexos nao possui opcoes ocultas"
  Assert-MatchText $script 'case ''toggle-chat-attach-menu'':[\s\S]*toggleChatAttachMenu\(\)[\s\S]*case ''chat-attach-option'':[\s\S]*handleChatAttachOption\(target\.dataset\.attachType\)[\s\S]*case ''open-chat-poll'':[\s\S]*showChatPollModal\(\)[\s\S]*case ''vote-chat-poll'':[\s\S]*votarEnqueteChat\(id, target\.dataset\.option\)' "acoes de menu criar e votar enquete estao conectadas"
  Assert-True -Condition ($script.Contains('const CHAT_EMOJIS = [') -and $script.Contains('function toggleChatEmojiMenu()') -and $script.Contains('function insertChatEmoji(emoji)') -and $script.Contains('setSelectionRange(cursor, cursor)')) -Message "chat possui seletor funcional de emojis"
  Assert-MatchText $script 'case ''toggle-chat-emoji-menu'':[\s\S]*toggleChatEmojiMenu\(\)[\s\S]*case ''insert-chat-emoji'':[\s\S]*insertChatEmoji\(target\.dataset\.emoji' "acoes de emoji do chat estao conectadas"
  Assert-MatchText $style '\.chat-attach-button[\s\S]*\.chat-attach-menu[\s\S]*\.poll-button[\s\S]*\.chat-poll-card[\s\S]*\.chat-poll-option[\s\S]*\.chat-poll-form[\s\S]*\.chat-poll-options-editor[\s\S]*\.chat-poll-option-editor[\s\S]*\.chat-poll-add-option[\s\S]*\.chat-poll-remove-option' "chat possui estilos para menu mais e enquetes"
  Assert-True -Condition ($style.Contains('.chat-emoji-button') -and $style.Contains('.chat-emoji-menu') -and $style.Contains('grid-template-columns: repeat(6, 34px)') -and $style.Contains('.chat-emoji-option')) -Message "chat possui estilos para menu de emojis"
  Assert-MatchText $style '\.chat-panel[\s\S]*grid-template-rows: auto auto minmax\(0, 1fr\) auto[\s\S]*\.chat-panel > \.panel-header[\s\S]*padding: 0 0 14px[\s\S]*\.chat-feed[\s\S]*background: transparent[\s\S]*\.chat-composer[\s\S]*margin-top: 8px' "chat preserva layout visual anterior"
  Assert-MatchText $script 'CHAT_FILE_ALLOWED_MIME_TYPES = new Set\(\[[\s\S]*"image/jpeg"[\s\S]*"image/png"[\s\S]*"image/gif"[\s\S]*"video/mp4"[\s\S]*"audio/mpeg"[\s\S]*"audio/wav"[\s\S]*"audio/ogg"[\s\S]*"audio/mp4"' "chat valida tipos de imagem video e audio"
  Assert-MatchText $script 'function validateChatFile\(file\).*CHAT_FILE_MAX_SIZE_BYTES' "chat valida tamanho do anexo"
  Assert-MatchText $script 'function getChatFileMimeType\(fileOrAttachment\).*split\(";"\)\[0\][\s\S]*CHAT_FILE_EXTENSION_MIME_TYPES' "chat normaliza MIME de audio com codecs ou extensao"
  Assert-MatchText $script 'upload\(path, file, \{ contentType: getChatFileMimeType\(file\), upsert: false \}\)' "upload de audio usa MIME normalizado"
  Assert-MatchText (Read-ProjectFile "vercel.json") '"Permissions-Policy", "value": "camera=\(\), microphone=\(self\), geolocation=\(\), payment=\(\), usb=\(\)"' "headers permitem microfone apenas no proprio site"
  Assert-MatchText $script 'function getSupportedChatAudioMimeType\(\)[\s\S]*audio/webm;codecs=opus[\s\S]*audio/mp4[\s\S]*MediaRecorder\.isTypeSupported' "chat escolhe MIME de audio suportado pelo navegador"
  Assert-MatchText $script 'function getChatAudioFileExtension\(mimeType = ""\)[\s\S]*audio/mp4[\s\S]*return "m4a"[\s\S]*audio/ogg[\s\S]*return "ogg"' "chat define extensao compativel para audio gravado"
  Assert-MatchText $script 'function toggleChatAudioRecording\(\).*navigator\.mediaDevices\?\.getUserMedia.*getSupportedChatAudioMimeType\(\)[\s\S]*new MediaRecorder\(chatAudioStream[\s\S]*new File\(\[blob\], `audio-chat-\$\{Date\.now\(\)\}\.\$\{extension\}`' "chat grava audio pelo navegador e gera arquivo com extensao correta"
  Assert-MatchText $script 'function formatAudioDuration\(totalSeconds\).*padStart\(2, "0"\).*function startChatAudioTimer\(\).*setInterval[\s\S]*updateChatAudioDuration' "chat mostra duracao atual durante gravacao"
  Assert-MatchText $style '\.record-audio-button\.is-recording[\s\S]*animation: recordingPulse[\s\S]*\.record-audio-button\.is-recording \.recording-duration[\s\S]*display: inline-block' "botao sinaliza visualmente quando audio esta gravando"
  Assert-True -Condition (-not $index.Contains('id="selected-file"')) -Message "chat nao usa mais o selected-file textual"
  Assert-True -Condition (-not $script.Contains('selected-file')) -Message "script nao manipula mais selected-file textual"
  Assert-MatchText $index 'id="chat-attachment-preview"[^>]*hidden[^>]*aria-live="polite"' "chat possui painel de previa para anexos"
  Assert-MatchText $script 'function syncChatFileInput\(\).*new DataTransfer\(\)[\s\S]*chatSelectedFiles\.forEach[\s\S]*input\.files = transfer\.files' "chat sincroniza multiplos anexos ao input"
  Assert-MatchText $script 'function setChatSelectedFile\(file\).*chatSelectedFiles = \[file\][\s\S]*renderChatAttachmentPreview\(chatSelectedFiles\)' "audio gravado e anexado ao input do chat com previa visual"
  Assert-MatchText $script 'function addChatSelectedFiles\(files\).*chatSelectedFiles = \[\.\.\.chatSelectedFiles, \.\.\.nextFiles\]' "chat permite adicionar mais de um arquivo simultaneamente"
  Assert-MatchText $script 'function renderChatAttachmentPreview\(files\).*URL\.createObjectURL\(file\)[\s\S]*chat-preview-image[\s\S]*chat-preview-audio-player[\s\S]*chat-preview-unavailable' "chat renderiza previa visual para imagem documento e audio selecionados"
  Assert-MatchText $script 'function clearChatSelectedFile\(\).*chatSelectedFiles = \[\][\s\S]*renderChatAttachmentPreview\(\[\]\)' "chat remove anexos selecionados pela previa"
  Assert-MatchText $script 'function previewChatSelectedFile\(index\).*chatAttachmentPreviewIndex = nextIndex[\s\S]*renderChatAttachmentPreview\(chatSelectedFiles\)' "clique no chip do chat abre a previa do anexo"
  Assert-MatchText $script 'data-action="preview-chat-file"[\s\S]*data-action="remove-chat-file"' "chip do chat visualiza e possui botao separado para remover"
  Assert-MatchText $script 'case ''remove-chat-file'':[\s\S]*removeChatSelectedFile\(target\.dataset\.index\)' "chat permite remover anexos individuais da previa"
  Assert-MatchText $script 'case ''preview-chat-file'':[\s\S]*previewChatSelectedFile\(target\.dataset\.index\)' "acao de visualizar anexo pelo chip esta conectada"
  Assert-True -Condition (-not $script.Contains('ðŸŽ™')) -Message "previa de audio nao usa emoji de microfone"
  Assert-MatchText $style '\.chat-attachment-preview[\s\S]*background: var\(--surface\)[\s\S]*\.chat-preview-image[\s\S]*object-fit: contain[\s\S]*\.chat-preview-unavailable[\s\S]*background: var\(--surface-soft\)[\s\S]*\.chat-preview-audio-card' "preview do composer usa tema claro do sistema"
  Assert-MatchText $style '\.chat-preview-chip-wrap[\s\S]*position: relative[\s\S]*\.chat-preview-chip-remove[\s\S]*position: absolute' "chip do chat tem remocao separada do clique de previa"
  Assert-MatchText $script 'function renderChatAttachment\(attachment\).*data-chat-image-preview.*data-chat-audio-preview' "chat renderiza previa de imagem e audio"
  Assert-MatchText $script 'function hydrateChatMediaPreviews\(\).*createPrivateStorageUrl\(bucket, path\)' "chat carrega previa privada com URL assinada"
  Assert-MatchText $script 'const path = `chat/\$\{channel\}/\$\{Date\.now\(\)\}-\$\{generateUUID\(\)\}-\$\{safeName\}`' "upload de chat grava em pasta por canal com nome unico"
  Assert-MatchText $script 'const CHAT_EDIT_WINDOW_MS = 15 \* 60 \* 1000' "edicao de mensagem possui limite de 15 minutos"
  Assert-MatchText $script 'function canEditChatMessage\(message\)[\s\S]*message\.autor !== getCurrentUserName\(\)[\s\S]*Date\.now\(\) - sentAt <= CHAT_EDIT_WINDOW_MS' "chat permite editar somente mensagem propria dentro do prazo"
  Assert-MatchText $script 'function editChatMessage\(id\)[\s\S]*updateItem\("comunicados"[\s\S]*serializeEditedChatMessage\(trimmed\)' "chat edita mensagem pelo PostgreSQL"
  Assert-MatchText $script 'function deleteChatMessage\(id\)[\s\S]*showConfirmActionModal[\s\S]*deleteItem\("comunicados", id\)' "chat exclui mensagem com confirmacao"
  Assert-MatchText $script 'function openChatMessageContextMenu\(event, id\)[\s\S]*canEdit \? ''<button type="button" data-chat-message-action="edit">Editar mensagem</button>'' : ""[\s\S]*data-chat-message-action="delete"[\s\S]*Excluir mensagem' "menu de contexto do chat exibe editar somente dentro do prazo e excluir sempre"
  Assert-MatchText $script 'chat-edited-label[\s\S]*Editada[\s\S]*data-chat-message-id="\$\{escapeHtml\(item\.id\)\}"[\s\S]*<time>\$\{escapeHtml\(messageTime\)\}</time>\$\{editedLabel\}' "mensagem editada mostra Editada ao lado do horario"
  Assert-MatchText $script 'data-action="add-board-list"[\s\S]*Adicionar coluna' "quadros possui mini coluna para adicionar coluna"
  Assert-MatchText $script 'function renderBoardListContextMenu\(\)[\s\S]*duplicate-list[\s\S]*Duplicar[\s\S]*rename-list[\s\S]*Renomear[\s\S]*delete-list[\s\S]*Excluir' "colunas dos quadros possuem menu de contexto"
  Assert-MatchText $script 'type === "list"[\s\S]*duplicate-list[\s\S]*rename-list[\s\S]*delete-list' "acoes de coluna dos quadros estao conectadas"
  Assert-MatchText $script 'function setupEquipeFormScrollGrid\(\)[\s\S]*equipe-workspace-expanded[\s\S]*equipe-two-col[\s\S]*offsetAfterForm: 140[\s\S]*expandOnce: true' "transicao da aba Equipe expande de forma estavel"
  Assert-True -Condition (-not ($index -match 'data-view="gerenciamento-vt"[^>]*>Gerenciamento VT</button>')) -Message "menu nao possui mais aba Gerenciamento VT"
  Assert-MatchText $index 'data-view="documentos-contratados"[^>]*>Documentos de Contratados</button>' "menu possui aba Documentos de Contratados"
  Assert-MatchText $index 'id="primary-sidebar"[^>]*aria-label="Navegacao principal"[\s\S]*id="mobile-menu-toggle"[^>]*aria-controls="primary-sidebar"[^>]*aria-expanded="false"' "mobile possui botao para abrir menu principal"
  Assert-MatchText $style '@media \(max-width: 900px\)[\s\S]*\.sidebar[\s\S]*position: fixed[\s\S]*transform: translateX\(-104%\)[\s\S]*\.app-shell\.mobile-menu-open \.sidebar[\s\S]*translateX\(0\)' "sidebar vira menu lateral no mobile"
  Assert-MatchText $style '\.mobile-menu-toggle[\s\S]*display: none[\s\S]*\.mobile-menu-backdrop[\s\S]*position: fixed' "menu mobile possui botao e backdrop"
  Assert-MatchText $style '@media \(max-width: 560px\)[\s\S]*\.topbar[\s\S]*flex-direction: row[\s\S]*\.panel[\s\S]*padding: 18px[\s\S]*\.channel-list[\s\S]*overflow-x: auto[\s\S]*\.chat-panel[\s\S]*minmax\(0, 1fr\)[\s\S]*\.form-grid[\s\S]*grid-template-columns: 1fr !important' "mobile possui layout compacto para paineis chat e formularios"
  Assert-MatchText $script 'function openMobileMenu\(\)[\s\S]*mobile-menu-backdrop[\s\S]*mobile-menu-open[\s\S]*aria-expanded", "true"' "script abre menu mobile com backdrop"
  Assert-MatchText $script 'function closeMobileMenu\(\)[\s\S]*mobile-menu-backdrop[\s\S]*classList\.remove\("mobile-menu-open"\)[\s\S]*aria-expanded", "false"' "script fecha menu mobile"
  Assert-MatchText $script 'mobile-menu-toggle"\)\?\.addEventListener\("click", toggleMobileMenu\)[\s\S]*event\.key === "Escape"[\s\S]*window\.innerWidth > 900' "menu mobile fecha por botao escape e resize"
  Assert-MatchText $script 'function setupUserMenuDropdown\(\)[\s\S]*user-menu-trigger[\s\S]*dataset\.menuReady[\s\S]*toggleUserMenuDropdown\(\)[\s\S]*dataset\.settingsTarget[\s\S]*showSettingsPanel\(panelId\)[\s\S]*renderAccountSettings\(\)[\s\S]*user-menu-logout[\s\S]*logout\(\)[\s\S]*DOMContentLoaded' "menu de usuario abre configuracoes pelo dropdown sem listeners duplicados"
  Assert-True -Condition (-not ($index -match 'trigger\.addEventListener\("click", toggleMenu\)')) -Message "menu de usuario nao possui script inline duplicado"
  Assert-True -Condition (-not ($index -match 'id="logout-button"|user-chip-caret')) -Message "topbar nao possui botao sair duplicado nem seta no chip de usuario"
  Assert-MatchText $index '<section class="view" id="conta"[\s\S]*class="settings-shell"[\s\S]*class="settings-panel"[\s\S]*id="settings-search-input"[\s\S]*id="settings-user-avatar"[\s\S]*id="settings-user-name"[\s\S]*id="settings-list"[\s\S]*Conta[\s\S]*Privacidade[\s\S]*Conversas[\s\S]*Notificacoes[\s\S]*Atalhos de teclado[\s\S]*id="settings-logout-button"[\s\S]*Desconectar[\s\S]*id="conta-form"[\s\S]*data-settings-panel="settings-shortcuts-panel"[\s\S]*</section>' "painel de configuracoes do usuario possui busca perfil secoes e desconectar"
  Assert-True -Condition (-not ([regex]::Match($index, '<section class="view" id="conta"[\s\S]*?</section>').Value -match 'Ajuda|feedback|Feedback')) -Message "painel de configuracoes nao possui ajuda ou feedback"
  Assert-MatchText $script 'const settingsLogoutButton = document\.getElementById\("settings-logout-button"\)[\s\S]*settingsLogoutButton\?\.addEventListener\("click", logout\)' "desconectar do painel usa fluxo de logout"
  Assert-MatchText $postgresClient '(readStoredSession|readSession)[\s\S]*window\.localStorage\.getItem\((sessionStorageKey|SESSION_STORAGE_KEY)\)' "sessao auth e restaurada do localStorage"
  Assert-MatchText $postgresClient 'persistSession[\s\S]*window\.localStorage\.setItem\((sessionStorageKey|SESSION_STORAGE_KEY), (serialized|raw)\)' "sessao auth persiste no localStorage"
  Assert-MatchText $postgresClient '(persistSession|clearSession)[\s\S]*window\.localStorage\.removeItem\((sessionStorageKey|SESSION_STORAGE_KEY)\)' "sessao auth limpa localStorage no logout"
  Assert-MatchText $postgresClient 'async getSession\(\)[\s\S]*action: "session"[\s\S]*persistSession\(session\)[\s\S]*async signOut\(\)[\s\S]*action: "logout"' "cliente auth restaura sessao por cookie sem quebrar DB"
  Assert-MatchText $script 'const POSTGRES_SESSION_KEY = "hub-postgres-session"[\s\S]*function getPersistedAuthFields\(\)[\s\S]*storageService\.getLocalItem\(POSTGRES_SESSION_KEY[\s\S]*postgresUser\?\.email' "F5 recupera identidade pela sessao postgres persistida"
  Assert-MatchText $script 'const PERSISTED_AUTH_USER_KEY = "hub-rh-persisted-auth-user"[\s\S]*storageService\.getLocalItem\(PERSISTED_AUTH_USER_KEY\)[\s\S]*storageService\.setLocalItem\(PERSISTED_AUTH_USER_KEY, persistedAuthUser\)[\s\S]*storageService\.removeLocalItem\(PERSISTED_AUTH_USER_KEY\)' "usuario autenticado persiste completo apos F5"
  Assert-MatchText $script 'function getCurrentUserRecord\(\)[\s\S]*storageService\.getLocalItem\(`\$\{SESSION_KEY\}-email`\)[\s\S]*storageService\.getSessionItem\(`\$\{SESSION_KEY\}-email`\)[\s\S]*function getCurrentUserName\(\)[\s\S]*storageService\.getLocalItem\(`\$\{SESSION_KEY\}-user`\)[\s\S]*storageService\.getSessionItem\(`\$\{SESSION_KEY\}-user`\)' "F5 usa usuario persistido igual a nova sessao do navegador"
  Assert-MatchText $script 'function isGenericAuthName\(value\)[\s\S]*normalized === "usuario"[\s\S]*function hasRealAuthIdentity\(authUser = \{\}\)[\s\S]*email \|\| !isGenericAuthName\(name\)[\s\S]*const hasValidDisplayIdentity = hasAuthSession && !isGenericAuthName\(getCurrentUserName\(\)\)[\s\S]*clearAuthenticatedUser\(\)[\s\S]*window\.location\.replace\(`login\.html\?next=' "Usuario generico exige novo login"
  Assert-MatchText (Read-ProjectFile "auth-display-guard.js") 'function verifyRenderedIdentity[\s\S]*name === "usuario"[\s\S]*redirectToLogin\(\)[\s\S]*function waitForAuthenticatedRender[\s\S]*__hubAuthReady[\s\S]*setTimeout\(\(\) => waitForAuthenticatedRender' "cabecalho aguarda sessao pronta antes de exigir novo login"
  Assert-MatchText $script 'window\.__hubAuthReady = true[\s\S]*document\.documentElement\.classList\.remove\("auth-entry-pending"\)' "index libera somente depois do perfil autenticado estar pronto"
  Assert-MatchText $script 'fetch\("/api/auth/heartbeat"[\s\S]*response\.status !== 401[\s\S]*clearAuthenticatedUser\(\)[\s\S]*window\.location\.replace\(`login\.html\?next=' "cliente envia sessao antiga para login"
  Assert-True -Condition (-not ((Read-ProjectFile "auth-entry.js") -match 'suspendPresenceOnReload|online: false|setTimeout\(resolve, 500\)')) -Message "F5 nao interrompe a inicializacao do sistema"
  Assert-MatchText (Read-ProjectFile "auth-entry.js") 'async function reauthenticateOnReload\(\)[\s\S]*O reload deve repetir a entrada normal[\s\S]*const authenticated = await reauthenticateInDatabase\(\)[\s\S]*window\.__hubAuthEntryPromise = reauthenticateOnReload\(\)' "F5 repete a entrada normal sem bloquear os scripts"
  Assert-MatchText $script 'clearLegacyTeamCredentials\(\)[\s\S]*const hasAuthSession = isLoginPage\(\) \? false : await restoreAuthenticatedSession\(\)' "reload continua o fluxo depois da reautenticacao"
  Assert-MatchText (Read-ProjectFile "auth-entry.js") 'LAST_ACCOUNT_KEY = "hub-rh-last-account"[\s\S]*readJson\(LAST_ACCOUNT_KEY\)[\s\S]*setItem\(LAST_ACCOUNT_KEY' "F5 preserva a ultima conta da maquina"
  Assert-MatchText $script 'const LAST_ACCOUNT_KEY = "hub-rh-last-account"[\s\S]*setLocalItem\(LAST_ACCOUNT_KEY[\s\S]*if \(window\.__hubReloadReauthenticated\)[\s\S]*await refreshSession\(\)' "F5 consulta perfil e dados do banco antes de liberar"
  Assert-MatchText (Read-ProjectFile "auth-entry.js") 'function renderAuthenticatedIdentity\(user\)[\s\S]*getElementById\("current-user"\)[\s\S]*window\.__hubAuthenticatedSession = result\.session' "sessao validada preenche o usuario antes do painel"
  Assert-MatchText $script 'const entrySession = window\.__hubAuthenticatedSession[\s\S]*entrySession\?\.user[\s\S]*postgresSession\?\.user \|\| entrySession\?\.user' "script restaura sessao entregue pelo autenticador"
  Assert-MatchText $script 'function getCurrentUserName\(\)[\s\S]*currentUserProfile\?\.nome[\s\S]*currentAuthUser\?\.user_metadata\?\.nome[\s\S]*find\(\(name\) => name && !isGenericAuthName\(name\)\)' "nome autenticado nao volta para Usuario generico"
  Assert-MatchText $script 'const profileName = profile\?\.nome \|\| ""[\s\S]*!isGenericAuthName\(profileName\)[\s\S]*const displayName' "perfil generico do banco nao substitui identidade autenticada"
  Assert-MatchText $script 'const hasAuthSession = isLoginPage\(\) \? false : await restoreAuthenticatedSession\(\)[\s\S]*const hasValidDisplayIdentity = hasAuthSession && !isGenericAuthName\(getCurrentUserName\(\)\)[\s\S]*if \(hasAuthSession && !hasValidDisplayIdentity\)[\s\S]*clearAuthenticatedUser\(\)[\s\S]*if \(!isLoginPage\(\) && !isPublicPage\(\)\)' "login manual rejeita usuario generico e nao restaura sessao"
  Assert-MatchText $script 'const hasAuthSession = isLoginPage\(\) \? false : await restoreAuthenticatedSession\(\)' "login nao restaura automaticamente a sessao anterior"
  Assert-MatchText (Read-ProjectFile "login-submit.js") 'form\.addEventListener\("submit"[\s\S]*event\.preventDefault\(\)[\s\S]*fetch\("/api/auth"[\s\S]*method: "POST"[\s\S]*persistSession\(result\.session\)[\s\S]*window\.location\.replace' "login intercepta o envio e autentica sem POST nativo"
  Assert-MatchText (Read-ProjectFile "login-submit.js") 'LAST_ACCOUNT_KEY[\s\S]*function clearStaleClientSession\(\)[\s\S]*clearStaleClientSession\(\)[\s\S]*fetch\("/api/auth"' "novo login limpa sessao antiga antes de autenticar"
  Assert-MatchText $script 'function setAuthenticatedUser\(authUser, profile = null\)[\s\S]*const persisted = getPersistedAuthFields\(\)[\s\S]*const hydratedAuthUser = hydratePersistedAuthUser\(authUser \|\| \{\}\)[\s\S]*if \(!profile && !hydratedAuthUser\?\.email && isGenericAuthName\(displayName\)\) return false[\s\S]*storageService\.setLocalItem\(`\$\{SESSION_KEY\}-user`, getLoginDisplayName\(displayName\)\)' "F5 nao sobrescreve usuario persistido real com Usuario"
  Assert-MatchText $script 'function hydratePersistedAuthUser\(authUser = \{\}\)[\s\S]*getPersistedAuthFields\(\)[\s\S]*const nome = authUser\?\.user_metadata\?\.nome[\s\S]*persisted\.nome[\s\S]*const email = authUser\?\.email \|\| persisted\.email[\s\S]*function buildPersistedAuthSession\(\)[\s\S]*const postgresSession = storageService\.getLocalItem\(POSTGRES_SESSION_KEY[\s\S]*const entrySession = window\.__hubAuthenticatedSession[\s\S]*hydratePersistedAuthUser\(persistedAuthUser \|\| postgresSession\?\.user \|\| entrySession\?\.user \|\| \{\}\)' "sessao restaurada reidrata nome email e cargo salvos"
  Assert-MatchText $script 'const profileFilters = \[[\s\S]*email \? `email\.ilike\.\$\{email\}` : ""[\s\S]*displayName && displayName !== "usuario" \? `nome\.ilike\.\$\{displayName\}` : ""[\s\S]*if \(!profileFilters\)[\s\S]*if \(profileFilters\) query = query\.or\(profileFilters\)' "perfil do DB nao usa filtro vazio nem nome generico Usuario"
  Assert-MatchText $script 'function hasPersistedAuthIdentity\(\)[\s\S]*hasRealAuthIdentity\(currentAuthUser\)[\s\S]*hasRealAuthIdentity\(currentUserProfile\)[\s\S]*hasRealAuthIdentity\(persistedAuthUser\)[\s\S]*function isAuthenticated\(\)[\s\S]*sessionIsActive && hasPersistedAuthIdentity\(\)' "sessao ativa sem usuario real nao libera o index"
  Assert-MatchText $script 'async function restoreAuthenticatedSession\(\)[\s\S]*const persistedSession = buildPersistedAuthSession\(\)[\s\S]*if \(persistedSession\?\.user\)[\s\S]*setAuthenticatedUser\(persistedSession\.user, null\)[\s\S]*refreshSession\(\);[\s\S]*return true;' "reload restaura sessao local imediatamente antes de consultar remoto"
  Assert-MatchText $script 'function setAuthenticatedUser\([\s\S]*renderCurrentUser\(\);[\s\S]*updateUserMenuHeader\(\);' "sessao restaurada atualiza o nome do usuario antes do painel"
  Assert-MatchText $script 'function withTimeout\(promise, ms, fallbackValue = null\)[\s\S]*setTimeout[\s\S]*async function restoreAuthenticatedSession\(\)[\s\S]*refreshSession = async \(\) =>[\s\S]*withTimeout\(getAuthSession\(\), 6000[\s\S]*withTimeout\(loadUserProfile\(sessionUser\), 6000' "refresh nao trava login aguardando auth perfil ou DB"
  Assert-MatchText $script 'const timeoutMarker = \{ timedOut: true \}[\s\S]*if \(authSession === timeoutMarker\)[\s\S]*if \(!authSession\?\.user\)[\s\S]*clearAuthenticatedUser\(\)[\s\S]*window\.location\.replace\(`login\.html\?next=' "sessao local invalida redireciona para login apos validar auth remoto"
  Assert-True -Condition (-not ($script -match 'catch\(\(error\)[\s\S]*if \(isAuthenticated\(\)\) \{[\s\S]*startAppInitialization\(\)')) -Message "erro de auth nao libera index privado com sessao local suspeita"
  Assert-MatchText $script 'const ACCOUNT_LOADING_REAUTH_MS = 2000[\s\S]*const POSTGRES_BOOT_TIMEOUT_MS = 8000' "HUB aguarda o PostgreSQL carregar os dados no F5"
  Assert-MatchText $script 'async function initializeAppData\(\)[\s\S]*if \(!isAuthenticated\(\)\)[\s\S]*window\.location\.replace[\s\S]*const postgresLoad = loadFromPostgreSQL\(\{ setupLive: true \}\)[\s\S]*withTimeout\(postgresLoad, POSTGRES_BOOT_TIMEOUT_MS, false\)[\s\S]*PostgreSQL carregando em segundo plano[\s\S]*classList\.remove\("is-locked"\)[\s\S]*classList\.add\("is-ready"\)' "HUB nao trava loading para usuario autenticado se PostgreSQL demorar"
  Assert-MatchText $script 'function unlockAccountLoadingWithSession\(\)[\s\S]*if \(!isAuthenticated\(\)\) return false;[\s\S]*classList\.remove\("is-locked"\)[\s\S]*classList\.add\("is-ready"\)[\s\S]*try \{[\s\S]*renderAll\(\)' "loading destrava antes da renderizacao e apenas com sessao autenticada"
  Assert-MatchText $script 'function armAccountLoadingReauth\(\)[\s\S]*setTimeout\(async \(\) =>[\s\S]*classList\.contains\("is-locked"\)[\s\S]*restoreAuthenticatedSession\(\)[\s\S]*withTimeout\(startAppInitialization\(\), POSTGRES_BOOT_TIMEOUT_MS, null\)[\s\S]*if \(!unlockAccountLoadingWithSession\(\)\)[\s\S]*window\.location\.replace' "loading da conta reautentica aguarda limite do DB e so redireciona sem sessao"
  Assert-MatchText $script 'async function initializeAppData\(\)[\s\S]*if \(!isAuthenticated\(\)\) \{[\s\S]*is-locked[\s\S]*window\.location\.replace\(`login\.html\?next=\$\{encodeURIComponent' "pagina privada sem sessao nao renderiza painel"
  Assert-MatchText $script 'catch\(\(error\)[\s\S]*if \(!isLoginPage\(\) && !isPublicPage\(\)\)[\s\S]*return;[\s\S]*if \(isPublicPage\(\)\) startAppInitialization\(\);' "falha de auth nao inicializa index privado"
  Assert-MatchText $script 'function showSettingsPanel\(panelId\)[\s\S]*data-settings-panel[\s\S]*classList\.toggle\("active"[\s\S]*data-settings-target' "script alterna secoes de configuracoes"
  Assert-MatchText $script 'function filterSettingsItems\(query\)[\s\S]*data-settings-target[\s\S]*button\.hidden = Boolean\(normalizedQuery\)' "script filtra itens de configuracoes"
  Assert-MatchText $index 'data-user-setting="hidePresence"[\s\S]*data-user-setting="blurChatPreviews"[\s\S]*data-user-setting="localPrivacyMode"[\s\S]*data-user-setting="compactMode"[\s\S]*data-user-setting="messageSize"[\s\S]*data-user-setting="showEmojiButton"[\s\S]*data-user-setting="enterToSend"[\s\S]*data-user-setting="notificationSound"[\s\S]*data-user-setting="desktopNotifications"[\s\S]*data-user-setting="dashboardNotificationBadges"[\s\S]*data-user-setting="keyboardShortcuts"' "configuracoes de usuario possuem opcionais funcionais"
  Assert-MatchText $script 'USER_SETTINGS_DEFAULTS[\s\S]*hidePresence[\s\S]*blurChatPreviews[\s\S]*compactMode[\s\S]*messageSize[\s\S]*showEmojiButton[\s\S]*enterToSend[\s\S]*notificationSound[\s\S]*desktopNotifications[\s\S]*dashboardNotificationBadges[\s\S]*keyboardShortcuts' "script define preferencias padrao do usuario"
  Assert-MatchText $script 'function loadUserSettings\(\)[\s\S]*localStorage\.getItem[\s\S]*migrateUserSettingsToCurrentKey\(settings\)[\s\S]*function saveUserSettings[\s\S]*localStorage\.setItem\(getUserSettingsStorageKey\(\)[\s\S]*function reloadUserSettingsForCurrentUser\(\)[\s\S]*currentUserSettings = loadUserSettings\(\)[\s\S]*function applyUserSettings\(\)[\s\S]*user-setting-compact[\s\S]*user-setting-blur-previews[\s\S]*chat-emoji-menu-wrap[\s\S]*dashboardNotificationBadges' "preferencias do usuario sao persistidas recarregadas e aplicadas por usuario"
  Assert-MatchText $script 'function updateUserSetting\(key, rawValue\)[\s\S]*saveUserSettings[\s\S]*applyUserSettings[\s\S]*requestDesktopNotificationPermission[\s\S]*document\.querySelectorAll\("\[data-user-setting\]"\)' "controles de configuracao atualizam preferencias"
  Assert-MatchText $script 'function handleSettingsKeyboardShortcut\(event\)[\s\S]*event\.key === "Escape"[\s\S]*closeActiveChat\(\)[\s\S]*if \(!currentUserSettings\.keyboardShortcuts\) return[\s\S]*event\.key\.toLowerCase\(\) === "k"[\s\S]*focusChatMessageFilter\(\)[\s\S]*\/\^\[0-9\]\$\/\.test\(event\.key\)[\s\S]*shortcutIndex = event\.key === "0" \? 9 : Number\(event\.key\) - 1[\s\S]*activateView\(button\.dataset\.view\)' "atalhos opcionais funcionam incluindo Ctrl K e Ctrl 0, com ESC essencial"
  Assert-MatchText $script 'function focusChatMessageFilter\(\)[\s\S]*activateView\("comunicacao"\)[\s\S]*chat-message-filter[\s\S]*filterInput\.select\(\)' "Ctrl K foca filtro de mensagens do chat"
  Assert-MatchText $script 'function syncChatMessageFilterVisibility\(\)[\s\S]*chat-message-filter-wrap[\s\S]*wrap\.hidden = !shouldShow[\s\S]*function clearChatMessageFilter\(\)[\s\S]*chatMessageFilterVisible = false[\s\S]*function resetChatComposerState\(\)[\s\S]*messageInput\.value = ""[\s\S]*clearChatSelectedFile\(\)[\s\S]*function closeActiveChat\(\)[\s\S]*activeChatChannel = ""[\s\S]*clearChatMessageFilter\(\)[\s\S]*resetChatComposerState\(\)[\s\S]*renderChatChannels\(\)[\s\S]*renderChat\(\)[\s\S]*event\.key === "Escape"[\s\S]*closeActiveChat\(\)' "filtro do chat aparece apenas por atalho e ESC fecha o chat ativo limpando composer"
  Assert-MatchText $script 'function getChatMessageFilterText\(item = \{\}\)[\s\S]*item\.autor[\s\S]*item\.mensagem[\s\S]*attachment\?\.name[\s\S]*chatMessageFilterQuery[\s\S]*getChatMessageFilterText\(item\)\.includes\(normalizedFilter\)' "chat filtra mensagens por texto autor data e anexo"
  Assert-MatchText $script 'function applyChatEditingShortcut\(key\)[\s\S]*normalizedKey === "b"[\s\S]*wrapChatSelection\("\*\*"\)[\s\S]*normalizedKey === "i"[\s\S]*wrapChatSelection\("_"\)[\s\S]*normalizedKey === "u"[\s\S]*wrapChatSelection\("<u>", "<\/u>"\)' "atalhos de edicao formatam texto do chat"
  Assert-MatchText $script 'function renderFormattedChatText\(message = ""\)[\s\S]*replace\(/\\\*\\\*\(\[\^\*\]\+\)\\\*\\\*\/g, "<strong>\$1<\/strong>"\)[\s\S]*replace\(/_\(\[\^_\]\+\)_\/g, "<em>\$1<\/em>"\)[\s\S]*&lt;u&gt;[\s\S]*<u>\$1<\/u>' "chat renderiza negrito italico e sublinhado"
  Assert-MatchText $script 'currentUserSettings\.enterToSend[\s\S]*event\.ctrlKey[\s\S]*chatForm\.requestSubmit\(\)' "opcao Enter envia mensagem controla envio do chat"
  Assert-MatchText $script 'function notifyUnreadRhMessages\(count\)[\s\S]*playUserNotificationSound\(\)[\s\S]*currentUserSettings\.desktopNotifications[\s\S]*Notification\.permission === "granted"[\s\S]*new Notification\(' "opcoes de notificacao emitem som e notificacao desktop"
  Assert-MatchText $style '\.user-setting-compact[\s\S]*\.user-setting-message-small[\s\S]*\.user-setting-message-large[\s\S]*\.user-setting-blur-previews[\s\S]*\.user-setting-hide-presence' "preferencias de usuario possuem estilos funcionais"
  Assert-MatchText $style '\.chat-message-filter[\s\S]*\.chat-message-filter input[\s\S]*\.chat-message-filter:focus-within' "filtro de mensagens possui estilo dedicado"
  Assert-MatchText $style '\.settings-shell[\s\S]*grid-template-columns[\s\S]*\.settings-panel[\s\S]*\.settings-search[\s\S]*\.settings-user-card[\s\S]*\.settings-item[\s\S]*\.settings-logout[\s\S]*\.settings-detail-panel\.active' "painel de configuracoes possui estilos dedicados"
  Assert-MatchText $index '<section class="view" id="documentos-contratados"[\s\S]*documentos-fredy\.html[\s\S]*documentos-besten\.html[\s\S]*documentos-achei\.html[\s\S]*documentos-trinca\.html[\s\S]*id="documentos-contratados-list"' "aba de documentos de contratados possui links e lista"
  Assert-MatchText $docsFredy 'data-contractor-password="fredy5212"[\s\S]*data-contractor-source="documentos-fredy\.html"[\s\S]*id="contractor-password-form"[\s\S]*public-password-control[\s\S]*data-toggle-public-password="contractor-access-password"[\s\S]*id="contratado-doc-form"[^>]*hidden[\s\S]*name="origem_html" type="hidden" value="documentos-fredy\.html"[\s\S]*id="contractor-documents-fields"[\s\S]*name="documentos" type="file" multiple required[\s\S]*id="adicionar-documento-contratado"[\s\S]*Adicionar documento[\s\S]*qualquer formato' "pagina Fredy exige senha registra origem aceita qualquer arquivo e adiciona documentos"
  Assert-MatchText ($docsBesten + $docsAchei + $docsTrinca) 'documentos-besten\.html[\s\S]*data-toggle-public-password="contractor-access-password"[\s\S]*documentos-achei\.html[\s\S]*data-toggle-public-password="contractor-access-password"[\s\S]*documentos-trinca\.html[\s\S]*data-toggle-public-password="contractor-access-password"' "paginas Besten Achei e Trinca possuem botao de exibir senha"
  Assert-MatchText $docsBesten 'data-contractor-password="besten5212"[\s\S]*data-contractor-source="documentos-besten\.html"[\s\S]*id="contractor-password-form"[\s\S]*public-password-control[\s\S]*id="contratado-doc-form"[^>]*hidden[\s\S]*name="origem_html" type="hidden" value="documentos-besten\.html"[\s\S]*id="contractor-documents-fields"[\s\S]*name="documentos" type="file" multiple required[\s\S]*id="adicionar-documento-contratado"[\s\S]*Adicionar documento[\s\S]*qualquer formato' "pagina Besten exige senha registra origem aceita qualquer arquivo e adiciona documentos"
  Assert-MatchText $docsAchei 'data-contractor-password="Achei5212"[\s\S]*data-contractor-source="documentos-achei\.html"[\s\S]*id="contractor-password-form"[\s\S]*public-password-control[\s\S]*id="contratado-doc-form"[^>]*hidden[\s\S]*name="origem_html" type="hidden" value="documentos-achei\.html"[\s\S]*id="contractor-documents-fields"[\s\S]*name="documentos" type="file" multiple required[\s\S]*id="adicionar-documento-contratado"[\s\S]*Adicionar documento[\s\S]*qualquer formato' "pagina Achei exige senha registra origem aceita qualquer arquivo e adiciona documentos"
  Assert-MatchText $docsTrinca 'data-contractor-password="trinca5212"[\s\S]*data-contractor-source="documentos-trinca\.html"[\s\S]*id="contractor-password-form"[\s\S]*public-password-control[\s\S]*id="contratado-doc-form"[^>]*hidden[\s\S]*name="origem_html" type="hidden" value="documentos-trinca\.html"[\s\S]*id="contractor-documents-fields"[\s\S]*name="documentos" type="file" multiple required[\s\S]*id="adicionar-documento-contratado"[\s\S]*Adicionar documento[\s\S]*qualquer formato' "pagina Trinca exige senha registra origem aceita qualquer arquivo e adiciona documentos"
  Assert-MatchText $docsFredy 'Checklist%20de%20Admissao%20-%20Empresas\.xlsx' "paginas de documentos possuem checklist para download"
  Assert-MatchText $docsFredy 'script\.js\?v=20260701-docs-label-download' "paginas de documentos quebram cache do script"
  Assert-MatchText $index '<section class="view" id="gerenciamento-vt"[\s\S]*<input name="id" type="hidden" />[\s\S]*id="vt-colaborador"[\s\S]*id="vt-mes"[\s\S]*id="vt-unidade"[\s\S]*id="vt-dias-uteis"[\s\S]*id="vt-valor-passagem"[\s\S]*id="vt-saldo-atual"[\s\S]*id="vt-valor-necessario"[\s\S]*id="cancelar-edicao-vt"[\s\S]*id="vt-registros-list"' "aba VT possui nome mes unidade e suporte a edicao"
  Assert-MatchText $index 'id="vt-colaborador"[^>]*pattern="\\S\+\\s\+\\S\+\.\*"[^>]*placeholder="Nome e sobrenome"[^>]*required' "VT exige nome e sobrenome do colaborador"
  Assert-MatchText $index 'id="vt-unidade"[^>]*required' "unidade do VT e obrigatoria"
  Assert-MatchText $index 'id="vt-mes"[^>]*required' "mes do VT e obrigatorio"
  Assert-MatchText $index 'id="vt-dias-uteis"[^>]*required' "dias uteis do VT e obrigatorio"
  Assert-MatchText $index 'id="vt-valor-passagem"[^>]*type="text"[^>]*inputmode="numeric"[^>]*pattern="\\d\+,\\d\{2\}"[^>]*required' "valor da passagem do VT usa formato x,xx e e obrigatorio"
  Assert-MatchText $index 'id="vt-saldo-atual"[^>]*required' "saldo atual do VT e obrigatorio"
  Assert-MatchText $index 'id="vt-mes" name="mes" required>[\s\S]*<option>Janeiro</option>[\s\S]*<option>Dezembro</option>' "campo de mes do VT registra somente o mes"
  Assert-MatchText $index 'panel-header vt-records-header[\s\S]*class="vt-filter-bar"[\s\S]*class="vt-filter-fields"[\s\S]*id="vt-filter-nome"[^>]*placeholder="Nome"[\s\S]*id="vt-filter-mes"[\s\S]*<option value="">[^<]*</option>[\s\S]*id="vt-filter-unidade"[^>]*data-unit-select[^>]*data-unit-placeholder="Unidade"[\s\S]*<button class="secondary-link compact-filter-button" id="limpar-filtros-vt"[^>]*hidden[^>]*>Limpar</button>' "aba VT possui filtros minimalistas no canto superior direito"
Assert-MatchText $index 'id="abrir-relatorio-vt"[^>]*type="button"[^>]*>' "aba VT possui botao de relatorio"
Assert-MatchText $index 'id="tracker-filter-type"[\s\S]*value="denuncia"[\s\S]*value="mensagem"[\s\S]*value="chamado"[\s\S]*value="vaga"' "menu de notificacoes filtra apenas tipos ativos"
Assert-True -Condition (-not ($index -match 'value="malote"|value="evento"|value="documento"|value="atestado"|value="quadro"|value="disciplinar"')) -Message "menu de notificacoes nao exibe tipos removidos"
Assert-MatchText $index 'id="abrir-relatorio-disciplinary"[^>]*type="button"[^>]*>' "aba advertencias e suspensoes possui botao de relatorio"
Assert-MatchText $index '<option>Anivers.rio de empresa</option>[\s\S]*id="edit-calendar-events"[^>]*>Editar eventos</button>' "calendario possui aniversario de empresa e botao para editar eventos"
Assert-MatchText $script 'function getCompanyBirthdayEvents\(\)[\s\S]*admissionDate = String\(item\.admissao[\s\S]*company-birthday-\$\{year\}-\$\{index\}[\s\S]*tipo: "Anivers.rio de empresa"[\s\S]*function isBirthdayEvent' "calendario gera aniversario de empresa pela data de admissao"
Assert-MatchText $script 'edit-calendar-events[\s\S]*eventos-list[\s\S]*scrollIntoView' "botao do calendario leva para lista de edicao"
Assert-MatchText $script "case 'editar-evento':[\s\S]*editarEvento\(id\)" "modal do calendario abre edicao de eventos"
Assert-MatchText $style '\.calendar-day\.has-birthday[\s\S]*rgba\(92, 65, 22, 0\.38\)[\s\S]*\.tag\.event-tag\.event-type-birthday[\s\S]*rgba\(202, 138, 4, 0\.18\)' "aniversarios usam cor mais apagada"
Assert-MatchText $companyBirthdays '"admissao"[\s\S]*"unidade"[\s\S]*"4- PL."[\s\S]*"28- ARA"' "planilha de aniversariantes inclui admissao e unidades oficiais"
  Assert-MatchText $script 'function calculateVtValue\(diasUteis, valorPassagem, saldoAtual\).*Math\.max\(0, \(Number\(diasUteis\).*Number\(valorPassagem\).*Number\(saldoAtual\)' "VT calcula dias uteis vezes passagem menos saldo"
  Assert-MatchText $script 'function parseBrazilianCurrency\(value\).*replace\(/\[\^\\d,\]/g, ""\).*replace\(",", "\."\)' "VT interpreta valor de passagem com virgula"
  Assert-MatchText $script 'function formatCurrencyInput\(value\).*replace\(/\\D/g, ""\).*`\$\{reais\},\$\{centavos\}`' "VT formata valor de passagem como x,xx"
  Assert-MatchText $script 'function getVtFormValues\(formElement\).*colaborador: String\(form\.get\("colaborador"\).*unidade: String\(form\.get\("unidade"\).*mes: String\(form\.get\("mes"\).*valorNecessario: calculateVtValue' "VT le colaborador unidade mes e valor calculado para registro"
  Assert-MatchText $script 'const VT_MONTH_NAMES = \["Janeiro"[\s\S]*"Dezembro"\][\s\S]*VT_MONTH_NAMES\.includes\(values\.mes\)' "VT valida o mes pelo nome sem ano"
  Assert-MatchText $script 'if \(!hasFullName\(values\.colaborador\)\)' "VT valida nome e sobrenome no script"
  Assert-MatchText $script 'vtRegistros: "hub_vt_registros"' "VT possui tabela PostgreSQL configurada"
  Assert-MatchText $script 'documentosContratados: "hub_documentos_contratados"' "documentos de contratados possuem tabela PostgreSQL configurada"
  Assert-MatchText $script 'CONTRACTOR_DOCUMENTS_BUCKET = "hub-contratados-documentos"' "documentos de contratados usam bucket privado dedicado"
  Assert-MatchText $script 'function validateContractorDocumentFile\(file\)[\s\S]*file\.size <= 0[\s\S]*CONTRACTOR_DOCUMENT_MAX_SIZE_BYTES[\s\S]*return null' "cliente aceita qualquer tipo de documento de contratado com limite de tamanho"
  Assert-MatchText $script 'function readFileAsDataUrl\(file\)[\s\S]*FileReader[\s\S]*readAsDataURL' "cliente consegue embutir arquivos quando necessario"
  Assert-MatchText $script 'async function buildContractorDocumentPayload\(documentos\)[\s\S]*type: String\(file\.type \|\| "application/octet-stream"\)[\s\S]*dataUrl: await readFileAsDataUrl\(file\)' "cliente monta documentos de contratado em data URL sem restringir MIME"
  Assert-MatchText $script 'function createContractorDocumentField\(required = false\)[\s\S]*name="documentos" type="file" multiple[\s\S]*remover-documento-contratado[\s\S]*addContractorDocumentButton\?\.addEventListener\("click"[\s\S]*insertAdjacentHTML\("beforeend", createContractorDocumentField\(false\)\)' "cliente adiciona campos extras para multiplos documentos com botao remover"
  Assert-MatchText $script 'contractorDocumentsFields\?\.addEventListener\("click"[\s\S]*remover-documento-contratado[\s\S]*fields\.length <= 1[\s\S]*return[\s\S]*closest\("\.contractor-document-field"\)\?\.remove\(\)' "cliente remove campo de documento somente quando houver mais de um"
  Assert-MatchText $script 'resetContractorDocumentFields\(contractorDocumentsFields\)[\s\S]*CPF j[aÃ¡] possui envio|CPF ja possui envio[\s\S]*Este CPF j[aÃ¡] possui um envio de documentos registrado' "cliente trata CPF duplicado em documentos de contratados"
  Assert-True -Condition (-not ($script -match 'addPendingContractorDocument\(localRecord\)|pendingSync: true[\s\S]*return localRecord')) -Message "documentos de contratados nao possuem sucesso somente local"
  Assert-MatchText $script 'if \(response\.ok\) \{[\s\S]*const savedRecord = mapContractorDocumentRow\(result\.data \|\| \{\}\)[\s\S]*data\.documentosContratados = mergeContractorDocuments\(\[savedRecord\], data\.documentosContratados \|\| \[\]\)[\s\S]*saveLocalData\(\)' "envio publico de documentos salva retorno bem-sucedido no cache local"
  Assert-MatchText $script 'const contractorPasswordForm = document\.getElementById\("contractor-password-form"\)[\s\S]*matchesContractorAccessPassword\(password, expectedPassword\)[\s\S]*contratadoDocForm\.hidden = false' "paginas de contratado liberam formulario somente com senha"
  Assert-MatchText $script 'function matchesContractorAccessPassword\(password, expectedPassword\)[\s\S]*charAt\(0\)\.toLocaleLowerCase\("pt-BR"\)[\s\S]*typedPassword\.slice\(1\) === targetPassword\.slice\(1\)[\s\S]*data-toggle-public-password[\s\S]*input\.type = isVisible \? "password" : "text"' "paginas de contratado aceitam primeira letra flexivel e exibem senha"
  Assert-MatchText $style '\.contractor-doc-container \.panel[\s\S]*box-shadow[\s\S]*\.public-password-control[\s\S]*grid-template-columns: minmax\(0, 1fr\) auto' "htmls de documentos possuem CSS robusto para senha"
  Assert-MatchText $script 'const contratadoDocForm = document\.getElementById\("contratado-doc-form"\)[\s\S]*const origemHtml = String\(form\.get\("origem_html"\)[\s\S]*submitPublicContractorDocuments\(\{ empresa, origemHtml, nome, telefone, cpf, documentos, accessPassword: contractorAccessPassword, turnstileToken \}\)' "formularios publicos de contratado enviam origem"
  Assert-MatchText $script 'function inferContractorDocumentSource\(origemHtml = "", empresa = ""\)[\s\S]*documentos-fredy\.html[\s\S]*documentos-besten\.html[\s\S]*documentos-achei\.html[\s\S]*documentos-trinca\.html' "documentos de contratados inferem origem pelo HTML ou empresa"
  Assert-MatchText $script 'function parseContractorDocumentsValue\(value\)[\s\S]*normalizeDoc[\s\S]*dataUrl: doc\.dataUrl \|\| doc\.data_url \|\| doc\.url[\s\S]*path: doc\.path \|\| doc\.storagePath \|\| doc\.storage_path[\s\S]*JSON\.parse\(value\)' "documentos de contratados aceitam array JSON string objeto e normalizam metadados"
  Assert-MatchText $script 'function mapContractorDocumentRow\(row = \{\}\)[\s\S]*origem_html \|\| row\.origemHtml[\s\S]*parseContractorDocumentsValue\(row\.documentos\)[\s\S]*pendingSync: Boolean\(row\.pendingSync\)' "documentos de contratados normalizam linhas do PostgreSQL e cache local"
  Assert-MatchText $script 'function getContractorSourceLabel\(origemHtml = "", empresa = ""\)[\s\S]*return "Fredy"[\s\S]*return "Besten"[\s\S]*return "Achei"[\s\S]*return "Trinca"' "documentos de contratados exibem origem como nome curto da empresa"
  Assert-MatchText $script 'function mergeContractorDocuments\(localItems = \[\], remoteItems = \[\]\)[\s\S]*inferContractorDocumentSource[\s\S]*getContractorDocumentIdentity' "documentos de contratados mesclam locais e PostgreSQL sem duplicar"
  Assert-MatchText $script 'CONTRACTOR_PENDING_DOCUMENTS_KEY = "hub-contractor-pending-documents"[\s\S]*function loadPendingContractorDocuments\(\)[\s\S]*getLocalItem\(CONTRACTOR_PENDING_DOCUMENTS_KEY' "documentos de contratados possuem fila persistente em localStorage"
  Assert-MatchText $script 'function removePendingContractorDocument\(id\)[\s\S]*loadPendingContractorDocuments\(\)\.filter[\s\S]*savePendingContractorDocuments\(remaining\)' "documentos de contratados removem fila persistente ao excluir"
  Assert-MatchText $script 'documentosContratados: \(parsed\.documentosContratados \|\| \[\]\)[\s\S]*filter\(\(item\) => !String\(item\.id \|\| ""\)\.startsWith\("local-"\) && !item\.pendingSync\)[\s\S]*map\(mapContractorDocumentRow\)' "carregamento local ignora documentos pendentes locais"
  Assert-True -Condition (-not ($script -match 'const localContractorDocuments = mergeContractorDocuments\(loadPendingContractorDocuments')) -Message "carregamento do PostgreSQL nao mescla documentos locais pendentes"
  Assert-MatchText $script 'function renderDocumentosContratados\(\)[\s\S]*const syncedItems = \(data\.documentosContratados \|\| \[\]\)\.filter\(\(item\) => !String\(item\.id \|\| ""\)\.startsWith\("local-"\) && !item\.pendingSync\)[\s\S]*documentos-contratados-list[\s\S]*item\.empresa[\s\S]*item\.origemHtml[\s\S]*formatContractorDocumentList' "HUB lista somente documentos sincronizados recebidos do PostgreSQL"
  Assert-MatchText $script 'function activateView\(viewId\)[\s\S]*viewId === "documentos-contratados"[\s\S]*refreshFromPostgreSQL\(\)' "aba documentos de contratados atualiza PostgreSQL ao abrir"
  Assert-MatchText $script 'getContractorSourceLabel\(item\.origemHtml, item\.empresa\)[\s\S]*Enviado por \$\{escapeHtml\(item\.nome' "HUB mostra origem curta e enviado pelo contratado"
  Assert-MatchText $script 'data-action="excluir-documento-contratado"[\s\S]*>Excluir</button>' "HUB possui botao para excluir documentos de contratado"
  Assert-MatchText $script 'async function excluirDocumentoContratado\(id\)[\s\S]*showPasswordActionModal[\s\S]*verifyAuthorizationPassword\(password\)[\s\S]*removePendingContractorDocument\(id\)[\s\S]*deleteItem\("documentosContratados", id\)' "exclusao de documentos de contratado exige senha e remove local/PostgreSQL"
  Assert-MatchText $script 'function formatContractorDocumentList\(documentos = \[\]\)[\s\S]*doc\.dataUrl[\s\S]*data-download-url[\s\S]*data-private-storage-name[\s\S]*data-private-storage-path' "HUB baixa documento embutido ou privado"
  Assert-MatchText $script 'async function downloadUrlAsBlob\(url, filename = "documento"\)[\s\S]*startsWith\("data:"\)[\s\S]*downloadBlob\(dataUrlToBlob\(url\), filename\)[\s\S]*return' "HUB baixa documentos embutidos por data URL sem fetch"
  Assert-MatchText $script 'function dataUrlToBlob\(dataUrl\)[\s\S]*atob\(base64\)[\s\S]*new Blob\(\[bytes\], \{ type: mimeType \}\)' "HUB converte data URL de documento em Blob"
  Assert-MatchText $script 'data-action="baixar-documento-rh"[^>]*>Gerar documento</button>' "Documentos RH usa acao manual para gerar documento"
  Assert-True -Condition (-not [regex]::IsMatch($script, 'data-doc-form[\s\S]{0,2500}downloadStyledRhDocument|data-doc-form[\s\S]{0,2500}downloadBlob')) -Message "Documentos RH nao baixa automaticamente ao salvar"
  Assert-MatchText $script 'async function downloadPrivateStorageFile\(bucket, value, filename = "documento"\)[\s\S]*createPrivateStorageUrl[\s\S]*link\.download[\s\S]*link\.click' "HUB baixa documento privado sem abrir automaticamente"
  Assert-MatchText $script 'downloadPrivateStorageFile\(\s*privateFileButton\.dataset\.privateStorageBucket[\s\S]*privateFileButton\.dataset\.privateStorageName' "clique em documento privado usa download"
  Assert-MatchText $script "case 'excluir-documento-contratado':\s*excluirDocumentoContratado\(id\);\s*break;" "acao de excluir documentos de contratado esta conectada"
  Assert-MatchText $script 'data-private-storage-bucket="\$\{CONTRACTOR_DOCUMENTS_BUCKET\}"' "lista abre documentos por URL privada"
  Assert-MatchText $script 'if \(collection === "vtRegistros"\)[\s\S]*dias_uteis: values\.diasUteis[\s\S]*valor_necessario: values\.valorNecessario' "VT envia payload para colunas do PostgreSQL"
  Assert-MatchText $script 'id\s*\?\s*await updateItem\("vtRegistros", id, \{ \.\.\.values, updatedBy: getCurrentUserName\(\) \}\)[\s\S]*:\s*await addItem\("vtRegistros", \{ \.\.\.values, createdBy: getCurrentUserName\(\) \}\)' "VT cria e edita registros pelo fluxo PostgreSQL"
  Assert-MatchText $script 'function renderVtRegistros\(\).*vt-registros-list[\s\S]*item\.colaborador[\s\S]*item\.unidade[\s\S]*formatVtMonth\(item\.mes\)[\s\S]*item\.valorNecessario' "VT exibe registros salvos com unidade e mes"
  Assert-MatchText $script 'function getFilteredVtRegistros\(\).*vt-filter-nome[\s\S]*vt-filter-mes[\s\S]*vt-filter-unidade[\s\S]*itemName\.includes\(nameFilter\)[\s\S]*item\.unidade !== unitFilter' "VT filtra registros por nome mes e unidade"
  Assert-MatchText $script 'function updateVtFilterClearButton\(\).*limpar-filtros-vt[\s\S]*hasActiveFilter[\s\S]*clearButton\.hidden = !hasActiveFilter[\s\S]*function renderVtRegistros\(\)[\s\S]*updateVtFilterClearButton\(\)' "botao limpar VT aparece somente com filtro ativo"
  Assert-MatchText $script 'document\.getElementById\("vt-filter-nome"\)\?\.addEventListener\("input", renderVtRegistros\)[\s\S]*document\.getElementById\("vt-filter-mes"\)\?\.addEventListener\("change", renderVtRegistros\)[\s\S]*document\.getElementById\("vt-filter-unidade"\)\?\.addEventListener\("change", renderVtRegistros\)[\s\S]*document\.getElementById\("limpar-filtros-vt"\)' "filtros de VT atualizam e limpam a lista"
Assert-MatchText $script 'document\.getElementById\("abrir-relatorio-vt"\)\?\.addEventListener\("click", showVtReportMenu\)' "botao de relatorio VT abre menu"
Assert-MatchText $script 'document\.getElementById\("abrir-relatorio-disciplinary"\)\?\.addEventListener\("click", showDisciplinaryReportMenu\)' "botao de relatorio disciplinar abre menu"
Assert-MatchText $script "case 'gerar-relatorio-disciplinary': gerarRelatorioDisciplinary\(target\.dataset\.scope\); break;" "acao de gerar relatorio disciplinar esta conectada"
Assert-MatchText $script 'sourceData\.candidaturas[\s\S]*type: "vaga"[\s\S]*Curriculo -' "acompanhamento inclui curriculos recebidos"
Assert-True -Condition (-not ($script -match 'sourceData\.malotes|sourceData\.quadros|sourceData\.disciplinaryRecords|sourceData\.atestados|\(sourceData\.documentosContratados|const docs = typeof documentRecords|const upcoming = typeof getUpcomingEvents')) -Message "acompanhamento nao inclui malotes eventos documentos quadros atestados ou disciplinares"
Assert-MatchText $script 'let allDashboardActivityItems = \[\][\s\S]*allDashboardActivityItems = sortedDashboardItems[\s\S]*visibleDashboardActivityItems = visibleDashboardItems[\s\S]*if \(dashboardActivityItemsReady\)[\s\S]*dashboardItems\.forEach' "modal acompanhar mantem historico completo enquanto painel mostra nao lidas"
Assert-MatchText $script 'nextDashboardButton\.textContent = "Ver proximas"[\s\S]*Novidades ocultas pelas suas configuracoes[\s\S]*Nenhuma pendencia para acompanhar[\s\S]*String\(item\.text\)\.length > 96 \? "\.\.\."' "activity-list do acompanhamento nao renderiza caracteres quebrados"
Assert-MatchText $script 'function showVtReportMenu\(\).*data-action="gerar-relatorio-vt" data-scope="filtered"[\s\S]*data-action="gerar-relatorio-vt" data-scope="all"' "menu de relatorio VT permite exportar filtrados ou todos"
  Assert-MatchText $script 'function createVtReportXlsxBlob\(rows\).*"\[Content_Types\]\.xml"[\s\S]*xl/workbook\.xml[\s\S]*xl/styles\.xml[\s\S]*xl/worksheets/sheet1\.xml' "relatorio VT gera estrutura xlsx valida com estilos"
  Assert-True -Condition (-not $script.Contains('worksheetRowXml(["Escopo"')) -Message "relatorio VT nao possui linha de escopo"
  Assert-MatchText $script 'function formatVtReportDateTime\(value = new Date\(\)\).*hour: "2-digit"[\s\S]*minute: "2-digit"[\s\S]*replace\(/\(\\d\{1,2\}:\\d\{2\}\):\\d\{2\}/, "\$1"\)' "relatorio VT remove segundos das datas"
  Assert-MatchText $script 'const headers = \["Colaborador", "Unidade", "M.s", "Dias .teis", "Valor da passagem", "Saldo atual", "Valor necess.rio", "Registrado em"\]' "relatorio VT remove registrado por"
  Assert-MatchText $script 'worksheetRowXml\(\["Relat.rio de Vale Transporte"\], 1, 2\)[\s\S]*worksheetRowXml\(\[`Gerado em \$\{formatVtReportDateTime\(new Date\(\)\)\}`\], 2, 2\)' "relatorio VT destaca nome e data de geracao"
  Assert-MatchText $script '<mergeCells count="2"><mergeCell ref="A1:H1"/><mergeCell ref="A2:H2"/></mergeCells>[\s\S]*alignment horizontal="center" vertical="center"' "relatorio VT centraliza nome e data de geracao"
  Assert-MatchText $script 'worksheetRowXml\(headers, 5, 1\)[\s\S]*<cellXfs count="4">[\s\S]*applyFont="1" applyFill="1"' "linha 5 do relatorio VT possui destaque"
  Assert-MatchText $script 'function gerarRelatorioVt\(scope = "filtered"\).*createVtReportXlsxBlob\(rows\)[\s\S]*safeDownloadName\(`relatorio-vt-\$\{useFilters \? "filtrado" : "todos"\}`, "xlsx"\)' "relatorio VT baixa arquivo xlsx"
  Assert-MatchText $script "case 'gerar-relatorio-vt': gerarRelatorioVt\(target\.dataset\.scope\); break;" "acao de gerar relatorio VT esta conectada"
  Assert-MatchText $script 'function renderVtRegistros\(\).*data-action="editar-vt"' "VT exibe botao para editar registro"
  Assert-MatchText $script 'function renderVtRegistros\(\).*data-action="excluir-vt"' "VT exibe botao para apagar registro"
  Assert-MatchText $script 'function editarVtRegistro\(id\).*form\.elements\.id\.value = registro\.id[\s\S]*form\.elements\.colaborador\.value = registro\.colaborador[\s\S]*setFieldValue\(form\.elements\.unidade[\s\S]*setFieldValue\(form\.elements\.mes[\s\S]*button\[type="submit"\]\x27\)\.textContent = "Salvar' "VT preenche formulario para editar registro"
  Assert-MatchText $script 'function resetVtForm\(\).*form\.elements\.id\.value = ""[\s\S]*cancelar-edicao-vt[\s\S]*button\[type="submit"\]\x27\)\.textContent = "Registrar' "VT cancela edicao e volta para cadastro"
  Assert-MatchText $script 'async function excluirVtRegistro\(id\).*showConfirmActionModal[\s\S]*deleteItem\("vtRegistros", id\)' "VT confirma e apaga registro pelo fluxo PostgreSQL"
  Assert-MatchText $script "case 'editar-vt': editarVtRegistro\(id\); break;" "acao de editar VT esta conectada"
  Assert-MatchText $script "case 'excluir-vt': excluirVtRegistro\(id\); break;" "acao de apagar VT esta conectada"
  Assert-MatchText $script 'vtForm\.addEventListener\("input", updateVtCalculation\)' "VT atualiza calculo automaticamente"
  Assert-MatchText $script 'function renderItemSizeOptions\(type = "epi", selectedSize = "", itemName = ""\).*"EXG"' "tamanho EXG esta cadastrado"
  Assert-MatchText $script 'const isShoe = /sapat/i\.test\(itemName\)' "sapato usa regra propria de numeracao"
  Assert-MatchText $index 'name="codigo_solicitacao"[^>]*maxlength="6"[^>]*pattern="\\d\{4\}-\\d"[^>]*placeholder="xxxx-x"' "cadastro de malote usa formato xxxx-x e limita o codigo"
  Assert-MatchText $index 'Buscar por C.digo da Solicita..o[\s\S]*id="malote-code-search"[^>]*type="search"[^>]*maxlength="6"[^>]*placeholder="xxxx-x"' "busca de malotes usa nome e placeholder do Codigo da Solicitacao"
  Assert-MatchText $index 'id="malote-filter-colaborador"[^>]*placeholder="Colaborador"' "malotes possuem filtro por colaborador"
  Assert-MatchText $index 'id="malote-status-filter"[\s\S]*value="Entrega"[\s\S]*Entregues[\s\S]*value="Separacao"[\s\S]*Em separa' "malotes possuem filtro por status de entrega ou separacao"
  Assert-MatchText $script 'malote-status-filter[\s\S]*normalizeEventType\(item\.status\) !== selectedStatus[\s\S]*addEventListener\("change"[\s\S]*renderAll' "script filtra malotes por status"
  Assert-MatchText $script 'function getMaloteCodeSearch\(\)' "script le busca por codigo de malote"
  Assert-MatchText $script 'function formatRequestCode\(value\).*slice\(0, 5\).*`\$\{digits\.slice\(0, 4\)\}-\$\{digits\.slice\(4\)\}`' "codigo da solicitacao limita 5 digitos e formata xxxx-x"
  Assert-MatchText $script 'malote-code-search"[\s\S]*field\.value = formatRequestCode\(field\.value\)' "busca de malotes formata codigo como xxxx-x"
  Assert-MatchText $script 'codeDigits\.includes\(searchDigits\) \|\| idDigits\.includes\(searchDigits\)' "filtro de malotes busca por codigo de solicitacao ou id"
  Assert-MatchText $index 'id="adicionar-colaborador-malote"[^>]*>Adicionar colaborador</button>' "malote possui botao para adicionar colaborador"
  Assert-MatchText $index 'name="malote_colaborador\[\]"[^>]*pattern="\\S\+\\s\+\\S\+\.\*"[^>]*placeholder="Nome e sobrenome"[^>]*required' "malote exige nome e sobrenome do colaborador que recebe"
  Assert-MatchText $script 'function readMaloteCollaborators\(formElement\).*data-malote-collaborator[\s\S]*malote_colaborador\[\][\s\S]*readEpiItems\(block\)' "malote vincula itens ao colaborador"
  Assert-MatchText $script 'adicionar-colaborador-malote[\s\S]*insertAdjacentHTML\("afterbegin", createMaloteCollaboratorBlock\(\)\)' "novo colaborador do malote aparece acima dos anteriores"
  Assert-MatchText $script 'function hasFullName\(value\).*\\S\+\\s\+\\S\+' "malote valida nome e sobrenome no script"
  Assert-MatchText $script 'colaboradores,\s*epis: formatEpiItems\(epiItems\)' "malote salva colaboradores junto dos itens"
  Assert-MatchText $script 'function normalizeMaloteCollaborators\(malote = \{\}\).*malote\.colaboradores[\s\S]*parseEpiItems\(malote\.epis\)' "malote mantem compatibilidade com registros antigos"
  Assert-MatchText $style '\.malote-collaborator \{[\s\S]*border: 2px solid var\(--teal\)[\s\S]*border-top: 6px solid var\(--teal\)' "quadro de colaborador possui contorno destacado"
  Assert-MatchText $style 'malote-collaborator-items::before[\s\S]*EPIs e Uniformes deste colaborador' "itens de EPI e uniforme por colaborador possuem destaque visual"
  Assert-MatchText $style '\.vt-records-header[\s\S]*align-items: flex-start[\s\S]*\.vt-filter-bar[\s\S]*justify-items: end[\s\S]*margin-left: auto[\s\S]*\.vt-report-button[\s\S]*border-radius: 999px[\s\S]*\.vt-filter-fields[\s\S]*grid-template-columns: 120px 105px 130px[\s\S]*border-radius: 999px[\s\S]*\.vt-filter-bar \.compact-filter-button[\s\S]*justify-self: end' "filtros e relatorio de VT ficam minimalistas no canto superior direito"
  Assert-MatchText $style '\.vt-report-modal \.modal-body[\s\S]*\.vt-report-options[\s\S]*\.vt-report-options \.report-chip' "menu de relatorio VT possui estilo dedicado"
  Assert-MatchText $style '\.contractor-company-logo[\s\S]*object-fit: contain[\s\S]*\.contractor-file-list' "paginas de documentos de contratado possuem estilo dedicado"
  Assert-MatchText $style '\.contractor-document-field[\s\S]*grid-template-columns: 1fr auto[\s\S]*\.contractor-remove-document-button[\s\S]*var\(--danger\)' "paginas de contratado possuem estilo para remover documentos extras"
  Assert-MatchText $style '\.contractor-company-logo-wide[\s\S]*width: 220px' "logo ampla da Trinca possui ajuste visual"
  Assert-MatchText $chamados 'id="adicionar-colaborador-chamado"[^>]*>Adicionar colaborador</button>' "chamados possuem botao para adicionar colaborador"
  Assert-MatchText $chamados 'name="chamado_colaborador\[\]"[^>]*pattern="\\S\+\\s\+\\S\+\.\*"[^>]*placeholder="Nome e sobrenome"[^>]*required' "chamados exigem nome e sobrenome do colaborador que recebe"
  Assert-MatchText $script 'function readChamadoCollaborators\(formElement\).*data-chamado-collaborator[\s\S]*chamado_colaborador\[\][\s\S]*readEpiItems\(block\)' "chamados vinculam itens ao colaborador"
  Assert-MatchText $script 'adicionar-colaborador-chamado[\s\S]*insertAdjacentHTML\("afterbegin", createChamadoCollaboratorBlock\(\)\)' "novo colaborador do chamado aparece acima dos anteriores"
  Assert-MatchText $script 'function flattenCollaboratorItems\(groups\).*nome: `\$\{group\.colaborador\} - \$\{item\.nome\}`' "chamados preservam colaborador junto do item enviado"
  Assert-MatchText $index 'class="panel-header chamados-records-header"[\s\S]*id="chamado-filter-colaborador"[^>]*placeholder="Colaborador"[\s\S]*id="chamado-filter-codigo"[^>]*maxlength="6"[^>]*placeholder="xxxx-x"[\s\S]*id="chamado-filter-mes"[\s\S]*id="chamado-filter-destino"[^>]*data-unit-select[^>]*data-unit-placeholder="Unidade"[\s\S]*id="limpar-filtros-chamados"[^>]*hidden' "aba chamados possui filtros por colaborador codigo mes e unidade"
  Assert-MatchText $script 'function getChamadosFilterValues\(\).*chamado-filter-destino[\s\S]*chamado-filter-colaborador[\s\S]*chamado-filter-codigo[\s\S]*chamado-filter-mes' "script le filtros de chamados"
  Assert-MatchText $script 'function filterChamadosByCurrentFilters\(items = \[\]\).*filters\.destino[\s\S]*getChamadoCollaboratorSearchText\(item\)[\s\S]*getChamadoSearchCode\(item\)[\s\S]*getChamadoCreatedMonth\(item\)' "script filtra chamados por destino colaborador codigo e mes"
  Assert-MatchText $script 'function formatChamadoFilterCode\(value = ""\).*replace\(/\\D/g, ""\).*`\$\{digits\.slice\(0, 4\)\}-\$\{digits\.slice\(4\)\}`' "filtro de codigo do chamado formata xxxx-x"
  Assert-MatchText $script 'document\.getElementById\("chamado-filter-destino"\)\?\.addEventListener\("change", renderChamadosSection\)[\s\S]*chamado-filter-colaborador[\s\S]*chamado-filter-codigo[\s\S]*formatChamadoFilterCode[\s\S]*chamado-filter-mes[\s\S]*limpar-filtros-chamados' "filtros de chamados atualizam e limpam a lista"
  Assert-MatchText $style '\.chamados-records-header[\s\S]*align-items: flex-start[\s\S]*\.chamados-filter-bar[\s\S]*justify-items: end[\s\S]*\.chamados-filter-fields[\s\S]*grid-template-columns: 120px 150px 86px 105px' "filtros de chamados ficam minimalistas no topo direito"
  Assert-MatchText $index 'name="unidade"[^>]*data-unit-select[^>]*required' "cadastro de vaga possui unidade destinada obrigatoria"
  Assert-MatchText $index 'id="vaga-filter-cargo"[^>]*list="vaga-cargo-options"[^>]*placeholder="Cargo"[\s\S]*id="vaga-cargo-options"' "aba vagas possui filtro de cargo"
  Assert-MatchText $script 'function updateVagaCargoFilterOptions[\s\S]*vaga-cargo-options[\s\S]*item\.cargo[\s\S]*filters\.cargo[\s\S]*item\.cargo' "script filtra vagas internas por cargo"
  Assert-MatchText $vagas 'id="public-vaga-cargo-filter"[^>]*list="public-vaga-cargo-options"[\s\S]*id="public-vaga-cidade-filter"[^>]*list="public-vaga-cidade-options"[\s\S]*id="clear-public-vaga-filters"[^>]*hidden' "html publico de vagas possui filtros por cargo e cidade"
  Assert-True -Condition (-not ($vagas -match 'public-vaga-unidade-filter|public-vaga-unidade-options')) -Message "html publico de vagas nao possui filtro de unidade"
  Assert-MatchText $script 'function updatePublicVagaFilterOptions\(openVagas = \[\]\).*public-vaga-cargo-options[\s\S]*public-vaga-cidade-options[\s\S]*getPublicVagaCidade' "opcoes de filtros publicos variam conforme vagas abertas"
  Assert-MatchText $script 'function getPublicVagaCidade\(vaga = \{\}\).*Cidade:' "portal de vagas extrai cidade da descricao da vaga"
  Assert-MatchText $script 'const cargoFilter = String\(publicVagaCargoFilter \|\| ""\).*const cidadeFilter = String\(publicVagaCidadeFilter \|\| ""\).*String\(v\.cargo \|\| ""\)\.toLowerCase\(\)\.includes\(cargoFilter\)[\s\S]*getPublicVagaCidade\(v\)\.toLowerCase\(\)\.includes\(cidadeFilter\)' "portal de vagas filtra por cargo e cidade"
  Assert-True -Condition (-not ($script -match 'publicVagaUnidadeFilter|public-vaga-unidade-filter|public-vaga-unidade-options')) -Message "script publico de vagas nao usa filtro de unidade"
  Assert-MatchText $script 'public-vaga-cargo-filter[\s\S]*publicVagaCargoFilter[\s\S]*public-vaga-cidade-filter[\s\S]*publicVagaCidadeFilter[\s\S]*clear-public-vaga-filters' "inputs publicos de vagas atualizam e limpam filtros"
  Assert-MatchText $script 'unidade: values\.unidade \|\| ""' "payload de vagas envia unidade destinada"
}

function Test-PublicSubmitFunction {
  $fn = Read-ProjectFile "postgres/functions/hub-public-submit/index.ts"
  $contractorApi = Read-ProjectFile "api/contractor-documents.js"

  Assert-MatchText $fn 'const ALLOWED_ORIGINS = new Set\(' "envio publico possui allowlist de origens"
  Assert-MatchText $fn 'if \(!hasAllowedOrigin\(req\)\) return json\(req, 403' "envio publico bloqueia origem nao permitida"
  Assert-MatchText $fn 'const RATE_LIMITS = \{[\s\S]*denuncias[\s\S]*chamados[\s\S]*candidaturas' "envio publico possui rate limit por tipo"
  Assert-MatchText $fn 'documentosContratados: \{ windowSeconds: 60 \* 30, max: 3 \}' "envio publico possui rate limit para documentos de contratados"
  Assert-MatchText $fn 'documentosContratados: "hub_documentos_contratados"' "envio publico grava documentos de contratados na tabela correta"
  Assert-MatchText $fn '"Fredy Pneus", "Besten Pneus", "Achei Pneus", "Trinca Mkt"' "Edge Function aceita Trinca Mkt como empresa de contratado"
  Assert-MatchText $fn 'documentos-\(fredy\|besten\|achei\|trinca\)\\\.html[\s\S]*origem_html: asText\(payload\.origemHtml\)[\s\S]*origemHtml: asText\(formData\.get\("origemHtml"\)\)' "Edge Function valida e grava origem do HTML"
  Assert-MatchText $fn 'CONTRACTOR_ACCESS_PASSWORDS[\s\S]*"Fredy Pneus": "fredy5212"[\s\S]*"Besten Pneus": "besten5212"[\s\S]*"Achei Pneus": "Achei5212"[\s\S]*"Trinca Mkt": "trinca5212"[\s\S]*Senha de acesso invalida' "Edge Function valida senha de acesso por empresa"
  Assert-MatchText $fn 'function normalizeSubmissionType\(value: unknown, payload: Record<string, unknown> = \{\}\)[\s\S]*documentoscontratados[\s\S]*documentosdecontratados[\s\S]*documentos[\s\S]*payload\.empresa[\s\S]*return "documentosContratados"' "Edge Function normaliza e infere tipo de documentos de contratados"
  Assert-MatchText $fn 'formData\.has\("empresa"\)[\s\S]*formData\.has\("documentos"\)[\s\S]*type = "documentosContratados"' "Edge Function infere documentos de contratado mesmo sem campo type"
  Assert-MatchText $fn 'normalizeContractorDocumentMimeType\(mimeType: unknown\)[\s\S]*application/octet-stream[\s\S]*validateContractorDocumentFile\(file: File \| null\)[\s\S]*file\.size <= 0 \|\| file\.size > CONTRACTOR_DOCUMENT_MAX_SIZE_BYTES[\s\S]*return null' "Edge Function aceita qualquer tipo de documento de contratado com limite de tamanho"
  Assert-True -Condition (-not $fn.Contains('validLength(normalizeContractorDocumentMimeType(item.type)')) -Message "Edge Function nao bloqueia documentos de contratado por MIME ou extensao"
  Assert-MatchText $fn 'type === "documentosContratados"[\s\S]*formData\.getAll\("documentos"\)[\s\S]*contratados/\$\{documentBatchId\}/\$\{safeName\}' "Edge Function monta paths privados para documento de contratado"
  Assert-MatchText $fn 'from\("hub-contratados-documentos"\)\s*[\s\S]*\.upload\(documentMeta\.path, file' "Edge Function envia documentos para bucket privado"
  Assert-MatchText $fn 'uploadedContractorPaths\.length[\s\S]*hub-contratados-documentos"\)\.remove\(uploadedContractorPaths\)' "Edge Function remove documentos se o registro falhar"
  Assert-MatchText $fn 'error\.code === "23505" && type === "documentosContratados"[\s\S]*CPF ja possui envio de documentos registrado' "Edge Function retorna mensagem clara para CPF duplicado em documentos"
  Assert-MatchText $fn 'hub_reserve_public_rate_limit' "envio publico reserva rate limit antes do insert"
  Assert-MatchText $fn 'hub_release_public_rate_limit' "envio publico libera rate limit em falha"
  Assert-MatchText $fn 'validateResumeFile\(file: File \| null\).*startsWith\(0x25, 0x50, 0x44, 0x46, 0x2d\).*startsWith\(0xd0, 0xcf, 0x11, 0xe0.*startsWith\(0x50, 0x4b, 0x03, 0x04\)' "curriculo valida assinatura real do arquivo na Edge Function"
  Assert-MatchText $fn 'TURNSTILE_SECRET_KEY' "envio publico suporta Turnstile quando configurado"
  Assert-MatchText $contractorApi 'runtime: "edge"[\s\S]*POSTGRES_SERVICE_ROLE_KEY[\s\S]*fileToDataUrl[\s\S]*origem_html[\s\S]*hub_documentos_contratados[\s\S]*request\.formData\(\)[\s\S]*PGRST204' "API Vercel salva documentos de contratados sem depender da Edge Function antiga e tolera schema antigo"
  Assert-MatchText $contractorApi 'result\?\.code === "23505"[\s\S]*CPF ja possui envio de documentos registrado' "API Vercel retorna mensagem clara para CPF duplicado"
}

function Test-MaloteDeleteFunction {
  $fn = Read-ProjectFile "postgres/functions/hub-malote-delete/index.ts"

  Assert-MatchText $fn 'admin\.auth\.getUser\(token\)' "exclusao de malote exige sessao valida"
  Assert-MatchText $fn 'from\("hub_users"\)\.select\("cargo"\)' "exclusao de malote consulta cargo do usuario"
  Assert-MatchText $fn '!== "rh".*Permissao insuficiente' "exclusao de malote exige cargo RH"
  Assert-MatchText $fn 'hub_get_action_password_hash' "exclusao de malote busca hash privado da senha de acao"
  Assert-MatchText $fn 'sha256\(password\).*passwordHash' "exclusao de malote compara hash da senha"
  Assert-MatchText $fn '\.from\("hub_malotes"\)\.delete\(\)\.eq\("id", id\)' "exclusao de malote deleta apenas o id solicitado"
}

function Test-RlsBaseline {
  $sql = Read-ProjectFile "postgres-rls-hub.sql"

  Assert-MatchText $sql 'alter table if exists public\.hub_denuncias enable row level security' "RLS habilitado em denuncias"
  Assert-MatchText $sql 'alter table if exists public\.hub_chat_messages enable row level security' "RLS habilitado em chat"
  Assert-MatchText $sql 'alter table if exists public\.hub_malotes enable row level security' "RLS habilitado em malotes"
  Assert-MatchText $sql 'alter table if exists public\.hub_chamados enable row level security' "RLS habilitado em chamados"
  Assert-MatchText $sql 'alter table if exists public\.hub_vagas enable row level security' "RLS habilitado em vagas"
  Assert-MatchText $sql 'alter table if exists public\.hub_vt_registros enable row level security' "RLS habilitado em registros de VT"
  Assert-MatchText $sql 'alter table if exists public\.hub_documentos_contratados enable row level security' "RLS habilitado em documentos de contratados"
  Assert-MatchText $sql 'create policy "hub_documentos_contratados_rh_all"[\s\S]*on public\.hub_documentos_contratados[\s\S]*app_private\.hub_is_rh\(\)' "documentos de contratados restritos ao RH"
  Assert-MatchText $sql 'create policy "hub_vt_registros_rh_all"[\s\S]*on public\.hub_vt_registros[\s\S]*app_private\.hub_is_rh\(\)' "registros de VT restritos ao RH"
  Assert-MatchText $sql 'drop policy if exists "hub_vagas_public_select_open"' "acesso anonimo direto a vagas e removido do baseline"
  Assert-MatchText $sql 'public = false[\s\S]*where id = ''hub-curriculos''' "bucket de curriculos e privado"
  Assert-MatchText $sql 'public = false[\s\S]*where id = ''hub-chat-files''' "bucket de anexos do chat e privado"
  Assert-MatchText $sql 'allowed_mime_types = array\[[\s\S]*''image/gif''[\s\S]*''video/mp4''[\s\S]*''video/webm''[\s\S]*''audio/mpeg''[\s\S]*''audio/wav''[\s\S]*''audio/ogg''[\s\S]*''audio/mp4''' "bucket de anexos permite imagens videos extras e audios"
  Assert-MatchText $sql '''hub-contratados-documentos''[\s\S]*false[\s\S]*10485760[\s\S]*null[\s\S]*hub_contratados_docs_rh_select' "bucket de documentos de contratados e privado aceita qualquer MIME"
  Assert-MatchText (Read-ProjectFile "postgres/migrations/20260702000100_allow_all_contractor_document_mime_types.sql") 'allowed_mime_types = null[\s\S]*where id = ''hub-contratados-documentos''' "migration garante qualquer MIME para documentos de contratados"
  Assert-MatchText (Read-ProjectFile "postgres/migrations/20260702000200_create_public_contractor_documents_rpc.sql") 'create or replace function public\.hub_submit_contractor_documents\(payload jsonb\)[\s\S]*security definer[\s\S]*jsonb_array_length\(v_documentos\) > 20[\s\S]*10485760[\s\S]*grant execute on function public\.hub_submit_contractor_documents\(jsonb\) to anon, authenticated' "RPC publica salva documentos de contratados aceitando qualquer tipo com senha e limite"
  Assert-MatchText (Read-ProjectFile "postgres/migrations/20260702000200_create_public_contractor_documents_rpc.sql") 'where cpf = v_cpf[\s\S]*CPF ja possui envio de documentos registrado' "RPC bloqueia mais de um envio por CPF"
  Assert-MatchText (Read-ProjectFile "postgres/migrations/20260702000300_limit_contractor_documents_one_per_cpf.sql") 'create unique index if not exists hub_documentos_contratados_cpf_unique[\s\S]*on public\.hub_documentos_contratados \(cpf\)' "banco limita documentos de contratado a um envio por CPF"
}

Test-LoginHtml
Test-ClientSecurityFunctions
Test-PublicSubmitFunction
Test-MaloteDeleteFunction
Test-RlsBaseline

Write-Host ""
Write-Host "Todos os testes unitarios passaram."


