create table if not exists public.hub_unit_test_runs (
  id bigint generated by default as identity primary key,
  test_suite text not null,
  status text not null check (status in ('passed', 'failed')),
  total_checks integer not null default 0,
  passed_checks integer not null default 0,
  failed_checks integer not null default 0,
  output text,
  commit_sha text,
  created_at timestamptz not null default now()
);

alter table public.hub_unit_test_runs enable row level security;

drop policy if exists "hub_unit_test_runs_rh_select" on public.hub_unit_test_runs;
drop policy if exists "hub_unit_test_runs_rh_insert" on public.hub_unit_test_runs;

create policy "hub_unit_test_runs_rh_select"
on public.hub_unit_test_runs
for select
to authenticated
using (app_private.hub_is_rh());

create policy "hub_unit_test_runs_rh_insert"
on public.hub_unit_test_runs
for insert
to authenticated
with check (app_private.hub_is_rh());
