create table if not exists public.hub_documentos_contratados (
  id bigint generated by default as identity primary key,
  empresa text not null check (empresa in ('Fredy Pneus', 'Besten Pneus', 'Achei Pneus', 'Trinca Mkt')),
  origem_html text not null default '' check (origem_html = '' or origem_html ~ '^documentos-(fredy|besten|achei|trinca)\.html$'),
  nome text not null check (char_length(nome) between 3 and 160),
  cpf text not null check (cpf ~ '^\d{3}\.\d{3}\.\d{3}-\d{2}$'),
  telefone text not null check (regexp_replace(telefone, '\D', '', 'g') ~ '^\d{10,11}$'),
  documentos jsonb not null default '[]'::jsonb,
  created_by text not null default 'Publico',
  created_at timestamptz not null default now()
);

alter table public.hub_documentos_contratados enable row level security;

grant select, insert, update, delete on public.hub_documentos_contratados to authenticated;
grant usage, select on sequence public.hub_documentos_contratados_id_seq to authenticated;

drop policy if exists "hub_documentos_contratados_rh_all" on public.hub_documentos_contratados;
create policy "hub_documentos_contratados_rh_all"
on public.hub_documentos_contratados
for all
to authenticated
using (app_private.hub_is_rh())
with check (app_private.hub_is_rh());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'hub-contratados-documentos',
  'hub-contratados-documentos',
  false,
  10485760,
  null
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "hub_contratados_docs_rh_select" on storage.objects;
drop policy if exists "hub_contratados_docs_rh_insert" on storage.objects;
drop policy if exists "hub_contratados_docs_rh_update" on storage.objects;
drop policy if exists "hub_contratados_docs_rh_delete" on storage.objects;

create policy "hub_contratados_docs_rh_select"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'hub-contratados-documentos'
  and app_private.hub_is_rh()
);

create policy "hub_contratados_docs_rh_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'hub-contratados-documentos'
  and app_private.hub_is_rh()
);

create policy "hub_contratados_docs_rh_update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'hub-contratados-documentos'
  and app_private.hub_is_rh()
)
with check (
  bucket_id = 'hub-contratados-documentos'
  and app_private.hub_is_rh()
);

create policy "hub_contratados_docs_rh_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'hub-contratados-documentos'
  and app_private.hub_is_rh()
);
